# Screening abnormal price-volume emiten IDX

Pipeline riset yang *reproducible*: ±960 emiten, 5 tahun data harian dari `yfinance`, target *future 20-trading-day abnormal price-volume event*, nonnegative weighted score (jumlah bobot = 1), Optuna dengan nested walk-forward validation, serta holdout 2026 yang tidak disentuh optimasi.

> **Anti-leakage:** seluruh fitur memakai informasi sampai tanggal scoring; label melihat 20 hari berikutnya; split diberi embargo 20 hari; 2026 tidak boleh dipakai memilih bobot atau threshold.

In [1]:
# Jalankan sekali bila environment belum siap:
# %pip install -q -r requirements.txt

from pathlib import Path
import json, math, warnings
from datetime import date

import numpy as np
import pandas as pd
import yfinance as yf
from tqdm.auto import tqdm
import optuna
from sklearn.metrics import average_precision_score
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore', category=FutureWarning)
pd.set_option('display.max_columns', 100)
SEED = 42
rng = np.random.default_rng(SEED)

## 1. Konfigurasi

`NOTEBOOK_DIR` dibuat tahan terhadap notebook yang dibuka dari root proyek maupun dari folder ini. Batas target default adalah hipotesis riset, bukan fakta universal; lakukan sensitivity analysis tanpa menyentuh holdout 2026.

In [2]:
cwd = Path.cwd().resolve()
NOTEBOOK_DIR = cwd if (cwd / 'config').exists() else cwd / 'Model Screening UMA'
ROOT = NOTEBOOK_DIR.parent
UNIVERSE_XLSX = ROOT / 'Analisis Pendahuluan' / 'KODE.xlsx'
CONTROL_CSV = NOTEBOOK_DIR / 'config' / 'control_universe.csv'
UMA_CSV = NOTEBOOK_DIR / 'config' / 'official_uma.csv'
RAW_DIR = NOTEBOOK_DIR / 'data' / 'raw'
PROCESSED_DIR = NOTEBOOK_DIR / 'data' / 'processed'
OUTPUT_DIR = NOTEBOOK_DIR / 'outputs'
for p in [RAW_DIR, PROCESSED_DIR, OUTPUT_DIR]: p.mkdir(parents=True, exist_ok=True)

TODAY = pd.Timestamp.today().normalize()
FINAL_TEST_START = pd.Timestamp('2026-01-01')
END_DATE = TODAY + pd.Timedelta(days=1)  # yfinance end bersifat exclusive
START_DATE = END_DATE - pd.DateOffset(years=5) - pd.Timedelta(days=45)
BENCHMARK = '^JKSE'
HORIZON = 20
TOP_K = 50
EMBARGO_DAYS = HORIZON
BATCH_SIZE = 80
FORCE_DOWNLOAD = False
N_TRIALS = 150

# Definisi event: dalam 20 hari ke depan, keduanya terjadi.
TARGET_ABNORMAL_RETURN = 0.10       # max cumulative stock return minus IHSG >= 10%
TARGET_MAX_VOLUME_RATIO = 2.50      # max volume / trailing median volume >= 2.5x
MIN_HISTORY = 120

FEATURES = [
    'mom_5', 'mom_20', 'mom_60', 'abret_5', 'abret_20',
    'volatility_20', 'volume_ratio_5_60', 'volume_z_20',
    'turnover_accel', 'range_20', 'drawdown_60'
]
print({'universe': str(UNIVERSE_XLSX), 'start': str(START_DATE.date()),
       'end': str(END_DATE.date()), 'final_test_start': str(FINAL_TEST_START.date())})

{'universe': '/Users/mraffyzeidan/Downloads/ISTL/Analisis Pendahuluan/KODE.xlsx', 'start': '2021-06-16', 'end': '2026-07-31', 'final_test_start': '2026-01-01'}

## 2. Universe dan data kontrol

IDX80/LQ45 tetap ada dalam training dan scoring. Flag kontrol hanya dipakai untuk mengeluarkan saham tersebut dari tabel kandidat final. File kontrol kosong akan memicu peringatan keras.

In [3]:
universe = pd.read_excel(UNIVERSE_XLSX, sheet_name=0)
universe.columns = universe.columns.str.strip()
universe = universe.rename(columns={'KODE': 'ticker', 'Sektor': 'sector', 'SubSektor': 'subsector'})
universe['ticker'] = universe['ticker'].astype(str).str.strip().str.upper().str.replace('.JK', '', regex=False)
universe = universe[universe['ticker'].str.match(r'^[A-Z0-9]+$')].drop_duplicates('ticker').reset_index(drop=True)
universe['yf_ticker'] = universe['ticker'] + '.JK'

controls = pd.read_csv(CONTROL_CSV)
controls['ticker'] = controls['ticker'].astype(str).str.strip().str.upper().str.replace('.JK', '', regex=False)
controls = controls[controls['ticker'].ne('') & controls['ticker'].ne('NAN')].copy()
for c in ['effective_from', 'effective_to']:
    controls[c] = pd.to_datetime(controls[c], errors='coerce')
control_tickers = set(controls['ticker'])
if not control_tickers:
    warnings.warn('control_universe.csv masih kosong. Isi riwayat IDX80/LQ45 sebelum hasil dipakai secara operasional.')

print(f'{len(universe):,} emiten | {len(control_tickers):,} ticker kontrol')
display(universe.head(), controls.head())

959 emiten | 0 ticker kontrol

/var/folders/m3/3gmfjhln13qbt6p_47473gs40000gn/T/ipykernel_19355/3529722015.py:15: UserWarning: control_universe.csv masih kosong. Isi riwayat IDX80/LQ45 sebelum hasil dipakai secara operasional.
  warnings.warn('control_universe.csv masih kosong. Isi riwayat IDX80/LQ45 sebelum hasil dipakai secara operasional.')

  ticker                      sector                subsector  Error yf_ticker
0   AADI                      Energi  Minyak, Gas & Batu Bara    NaN   AADI.JK
1   AALI      Barang Konsumen Primer        Makanan & Minuman    NaN   AALI.JK
2   ABBA  Barang Konsumen Non-Primer          Media & Hiburan    NaN   ABBA.JK
3   ABDA                    Keuangan                 Asuransi    NaN   ABDA.JK
4   ABMM                      Energi  Minyak, Gas & Batu Bara    NaN   ABMM.JK

Empty DataFrame
Columns: [ticker, index_name, effective_from, effective_to]
Index: []

## 3. Unduh 5 tahun data dengan `yfinance` + `tqdm`

Pengunduhan dilakukan per batch agar cepat dan tetap terlihat progresnya. Hasil dicache; ticker gagal dicatat dan dapat diulang dengan `FORCE_DOWNLOAD=True`.

In [4]:
def download_batch(symbols, start, end):
    raw = yf.download(
        tickers=symbols, start=start, end=end, interval='1d', auto_adjust=False,
        actions=False, group_by='ticker', threads=True, progress=False, timeout=30
    )
    frames = []
    if raw.empty:
        return frames
    if not isinstance(raw.columns, pd.MultiIndex):
        raw.columns = pd.MultiIndex.from_product([[symbols[0]], raw.columns])
    level0 = set(raw.columns.get_level_values(0))
    for symbol in symbols:
        if symbol not in level0:
            continue
        x = raw[symbol].copy().dropna(how='all')
        if x.empty:
            continue
        x.columns = x.columns.str.lower().str.replace(' ', '_')
        x = x.reset_index().rename(columns={'Date': 'date', 'index': 'date'})
        x['ticker'] = symbol.removesuffix('.JK')
        frames.append(x)
    return frames

cache_path = RAW_DIR / f'prices_{START_DATE:%Y%m%d}_{END_DATE:%Y%m%d}.parquet'
if cache_path.exists() and not FORCE_DOWNLOAD:
    prices = pd.read_parquet(cache_path)
else:
    symbols = universe['yf_ticker'].tolist() + [BENCHMARK]
    batches = [symbols[i:i+BATCH_SIZE] for i in range(0, len(symbols), BATCH_SIZE)]
    frames = []
    for batch in tqdm(batches, desc='Download batch', unit='batch'):
        frames.extend(download_batch(batch, START_DATE, END_DATE))
    prices = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    if prices.empty:
        raise RuntimeError('Tidak ada data yang berhasil diunduh.')
    prices['date'] = pd.to_datetime(prices['date']).dt.tz_localize(None)
    prices.to_parquet(cache_path, index=False)

prices['date'] = pd.to_datetime(prices['date']).dt.tz_localize(None)
prices = prices.sort_values(['ticker', 'date']).drop_duplicates(['ticker', 'date'])
downloaded = set(prices['ticker'])
missing = sorted(set(universe['ticker']) - downloaded)
pd.DataFrame({'ticker': missing}).to_csv(OUTPUT_DIR / 'missing_yfinance.csv', index=False)
print(f'Rows: {len(prices):,} | ticker berhasil: {len(downloaded):,} | gagal: {len(missing):,}')
display(pd.DataFrame({'ticker_gagal': missing}).head(20))

Download batch:   0%|          | 0/12 [00:00<?, ?batch/s]

$GOTOM.JK: possibly delisted; no timezone found

1 Failed download:
['GOTOM.JK']: possibly delisted; no timezone found

Rows: 1,022,421 | ticker berhasil: 959 | gagal: 1

  ticker_gagal
0        GOTOM

## 4. Feature engineering dan target

Semua rolling statistic digeser secara alami karena baris tanggal *t* hanya memakai data sampai penutupan *t*. Target memakai maksimum abnormal return dan volume ratio pada hari bursa `t+1 ... t+20`. Baris yang belum memiliki horizon penuh diberi label `NaN`, bukan nol.

In [5]:
benchmark_symbol = BENCHMARK.removesuffix('.JK')
# yfinance mempertahankan ^JKSE sebagai ticker; fallback aman untuk batch satu simbol.
bench_rows = prices[prices['ticker'].isin([BENCHMARK, benchmark_symbol, '^JKSE'])].copy()
if bench_rows.empty:
    b = yf.download(BENCHMARK, start=START_DATE, end=END_DATE, auto_adjust=False, progress=False)
    b = b.reset_index()
    if isinstance(b.columns, pd.MultiIndex): b.columns = b.columns.get_level_values(0)
    bench = b[['Date', 'Close']].rename(columns={'Date': 'date', 'Close': 'bench_close'})
else:
    bench = bench_rows[['date', 'close']].rename(columns={'close': 'bench_close'}).drop_duplicates('date')
bench['date'] = pd.to_datetime(bench['date']).dt.tz_localize(None)

stocks = prices[prices['ticker'].isin(set(universe['ticker']))].copy()
stocks = stocks.merge(bench, on='date', how='left').merge(
    universe[['ticker', 'sector', 'subsector']], on='ticker', how='left'
)

def future_rolling_max(s, horizon):
    # shift(-horizon) + rolling memberi jendela t+1..t+horizon tanpa loop Python.
    return s.iloc[::-1].rolling(horizon, min_periods=horizon).max().iloc[::-1].shift(-1)

def engineer_one(g):
    g = g.sort_values('date').copy()
    px = g['adj_close'].fillna(g['close']) if 'adj_close' in g else g['close']
    ret = px.pct_change()
    bret = g['bench_close'].pct_change()
    g['mom_5'] = px.pct_change(5)
    g['mom_20'] = px.pct_change(20)
    g['mom_60'] = px.pct_change(60)
    g['abret_5'] = g['mom_5'] - g['bench_close'].pct_change(5)
    g['abret_20'] = g['mom_20'] - g['bench_close'].pct_change(20)
    g['volatility_20'] = ret.rolling(20).std() * np.sqrt(252)
    vol_med_20 = g['volume'].rolling(20).median().replace(0, np.nan)
    vol_med_60 = g['volume'].rolling(60).median().replace(0, np.nan)
    g['volume_ratio_5_60'] = g['volume'].rolling(5).mean() / vol_med_60
    g['volume_z_20'] = (g['volume'] - g['volume'].rolling(20).mean()) / g['volume'].rolling(20).std()
    turnover = px * g['volume']
    g['turnover_accel'] = turnover.rolling(5).mean() / turnover.rolling(60).median()
    g['range_20'] = g['high'].rolling(20).max() / g['low'].rolling(20).min() - 1
    g['drawdown_60'] = px / px.rolling(60).max() - 1

    future_px_max = future_rolling_max(px, HORIZON)
    future_bench_max = future_rolling_max(g['bench_close'], HORIZON)
    future_abret = (future_px_max / px - 1) - (future_bench_max / g['bench_close'] - 1)
    future_vol_ratio = future_rolling_max(g['volume'], HORIZON) / vol_med_60
    has_full_horizon = g['date'].shift(-HORIZON).notna()
    g['future_max_abret_20'] = future_abret
    g['future_max_volume_ratio_20'] = future_vol_ratio
    g['target'] = np.where(
        has_full_horizon,
        ((future_abret >= TARGET_ABNORMAL_RETURN) &
         (future_vol_ratio >= TARGET_MAX_VOLUME_RATIO)).astype(float),
        np.nan
    )
    return g

parts = []
for _, g in tqdm(stocks.groupby('ticker', sort=False), total=stocks['ticker'].nunique(), desc='Features', unit='ticker'):
    parts.append(engineer_one(g))
panel = pd.concat(parts, ignore_index=True)
panel = panel.replace([np.inf, -np.inf], np.nan)
panel.to_parquet(PROCESSED_DIR / 'feature_panel.parquet', index=False)
print(panel[['date','ticker','target']].dropna().shape, 'positive rate =', panel['target'].mean())

Features:   0%|          | 0/958 [00:00<?, ?ticker/s]

(1002810, 3) positive rate = 0.18433102980624444

## 5. Cross-sectional transform dan metrik

Model utama sengaja transparan: fitur diubah menjadi percentile rank `[0,1]` per tanggal, arah fitur dipelajari sebagai tanda tetap dari training fold, lalu skor adalah kombinasi nonnegative dengan bobot berjumlah satu. Tidak ada fitting model nonlinear.

In [6]:
def add_cross_sectional_ranks(df, features):
    out = df.copy()
    for f in tqdm(features, desc='Cross-sectional ranks', unit='fitur'):
        out[f'r_{f}'] = out.groupby('date')[f].rank(pct=True, method='average')
    return out

panel = add_cross_sectional_ranks(panel, FEATURES)
RANK_FEATURES = [f'r_{f}' for f in FEATURES]

def precision_at_k(y, score, k=50):
    x = pd.DataFrame({'y': y, 's': score}).dropna().nlargest(k, 's')
    return float(x['y'].mean()) if len(x) else np.nan

def ndcg_at_k(y, score, k=50):
    x = pd.DataFrame({'y': y, 's': score}).dropna().sort_values('s', ascending=False).head(k)
    if x.empty: return np.nan
    gains = x['y'].to_numpy()
    discounts = 1 / np.log2(np.arange(2, len(x) + 2))
    dcg = np.sum(gains * discounts)
    ideal = np.sort(gains)[::-1]
    idcg = np.sum(ideal * discounts)
    return float(dcg / idcg) if idcg > 0 else 0.0

def datewise_topk_metrics(df, k=50):
    rows = []
    for d, x in df.groupby('date'):
        if x['target'].notna().sum() == 0: continue
        p = precision_at_k(x['target'], x['score'], k)
        n = ndcg_at_k(x['target'], x['score'], k)
        base = x['target'].mean()
        rows.append((d, p, n, p / base if base > 0 else np.nan))
    return pd.DataFrame(rows, columns=['date','precision_at_50','ndcg_at_50','lift_at_50'])

def score_frame(df, weights, directions):
    x = df.copy()
    z = x[RANK_FEATURES].fillna(0.5).to_numpy()
    z = np.where(np.asarray(directions)[None, :] > 0, z, 1-z)
    x['score'] = z @ np.asarray(weights)
    return x

def learn_directions(train):
    # Arah hanya dari training window; korelasi nol diarahkan positif.
    corr = train[RANK_FEATURES].corrwith(train['target'], method='spearman').fillna(0)
    return np.where(corr.to_numpy() >= 0, 1, -1)

def evaluate(df):
    x = df.dropna(subset=['target','score'])
    pr = average_precision_score(x['target'], x['score']) if x['target'].nunique() > 1 else np.nan
    daily = datewise_topk_metrics(x, TOP_K)
    return {'pr_auc': pr, 'ndcg_at_50': daily['ndcg_at_50'].mean(),
            'precision_at_50': daily['precision_at_50'].mean(),
            'lift_at_50': daily['lift_at_50'].mean()}

model_data = panel.dropna(subset=['target']).copy()
print(model_data['date'].min(), model_data['date'].max(), len(model_data))

Cross-sectional ranks:   0%|          | 0/11 [00:00<?, ?fitur/s]

2021-06-16 00:00:00 2026-07-02 00:00:00 1002810

## 6. Nested walk-forward + Optuna

Outer folds memberi estimasi performa yang tidak bias. Di setiap outer fold, Optuna hanya melihat inner folds yang seluruhnya berada sebelum outer validation. Objective persis:

`0.50*mean_pr_auc + 0.30*mean_ndcg@50 + 0.20*mean_precision@50 - 0.10*std(fold_pr_auc)`

In [7]:
def make_walk_forward_folds(dates, n_folds=4, min_train_months=18, valid_months=4, embargo_days=20):
    dates = pd.DatetimeIndex(sorted(pd.Series(dates).dropna().unique()))
    first = dates.min() + pd.DateOffset(months=min_train_months)
    last_start = dates.max() - pd.DateOffset(months=valid_months)
    starts = pd.date_range(first, last_start, periods=n_folds)
    folds = []
    for vs in starts:
        vs = dates[dates.searchsorted(vs)] if dates.searchsorted(vs) < len(dates) else None
        if vs is None: continue
        ve_target = vs + pd.DateOffset(months=valid_months)
        ve_idx = min(dates.searchsorted(ve_target), len(dates)-1)
        ve = dates[ve_idx]
        train_end = vs - pd.offsets.BDay(embargo_days)
        folds.append((dates.min(), train_end, vs, ve))
    return folds

def sample_simplex(trial, n):
    # Softmax parameterization menjamin nonnegative dan sum(weights)=1.
    logits = np.array([trial.suggest_float(f'logit_{i}', -4, 4) for i in range(n)])
    logits -= logits.max()
    w = np.exp(logits)
    return w / w.sum()

def optimize_weights(train_pool, inner_folds, n_trials=N_TRIALS):
    def objective(trial):
        weights = sample_simplex(trial, len(RANK_FEATURES))
        metrics = []
        for tr_start, tr_end, va_start, va_end in inner_folds:
            tr = train_pool[(train_pool.date >= tr_start) & (train_pool.date <= tr_end)]
            va = train_pool[(train_pool.date >= va_start) & (train_pool.date <= va_end)]
            if tr.empty or va.empty: continue
            directions = learn_directions(tr)
            metrics.append(evaluate(score_frame(va, weights, directions)))
        if len(metrics) < 2: return -1.0
        m = pd.DataFrame(metrics)
        return (0.50*m.pr_auc.mean() + 0.30*m.ndcg_at_50.mean()
                + 0.20*m.precision_at_50.mean() - 0.10*m.pr_auc.std(ddof=0))

    sampler = optuna.samplers.TPESampler(seed=SEED)
    study = optuna.create_study(direction='maximize', sampler=sampler)
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    return study, sample_simplex(study.best_trial, len(RANK_FEATURES))

development = model_data[model_data['date'] < FINAL_TEST_START].copy()
outer_folds = make_walk_forward_folds(development['date'], n_folds=4, min_train_months=24, valid_months=4)
outer_results, outer_weights = [], []

for fold_id, (tr_start, tr_end, va_start, va_end) in enumerate(tqdm(outer_folds, desc='Outer folds'), 1):
    outer_train = development[(development.date >= tr_start) & (development.date <= tr_end)]
    outer_valid = development[(development.date >= va_start) & (development.date <= va_end)]
    inner = make_walk_forward_folds(outer_train['date'], n_folds=3, min_train_months=12, valid_months=3)
    study, weights = optimize_weights(outer_train, inner)
    directions = learn_directions(outer_train)
    met = evaluate(score_frame(outer_valid, weights, directions))
    met.update({'fold': fold_id, 'train_end': tr_end, 'valid_start': va_start,
                'valid_end': va_end, 'inner_best_objective': study.best_value})
    outer_results.append(met)
    outer_weights.append(weights)

outer_results = pd.DataFrame(outer_results)
display(outer_results)
print('Outer PR-AUC instability:', outer_results['pr_auc'].std(ddof=0))

Outer folds:   0%|          | 0/4 [00:00<?, ?it/s]

[I 2026-07-30 09:27:00,466] A new study created in memory with name: no-name-18f094e4-7326-4fa9-a2e1-3658a14c10cb

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-07-30 09:27:01,930] Trial 0 finished with value: 0.3773051008529895 and parameters: {'logit_0': -1.0036790492211, 'logit_1': 3.6057144512793293, 'logit_2': 1.8559515344912407, 'logit_3': 0.7892678735762928, 'logit_4': -2.751850876460508, 'logit_5': -2.752043837310379, 'logit_6': -3.5353311026544043, 'logit_7': 2.9294091661994814, 'logit_8': 0.8089200939456704, 'logit_9': 1.664580622368364, 'logit_10': -3.8353240456335804}. Best is trial 0 with value: 0.3773051008529895.
[I 2026-07-30 09:27:03,256] Trial 1 finished with value: 0.3718194475540194 and parameters: {'logit_0': 3.7592788172959546, 'logit_1': 2.659541126403374, 'logit_2': -2.3012871145737908, 'logit_3': -2.545400262343195, 'logit_4': -2.5327639211725295, 'logit_5': -1.5660620563236982, 'logit_6': 0.19805145305790273, 'logit_7': -0.5444398508630739, 'logit_8': -1.6701668784156647, 'logit_9': 0.8948231577790358, 'logit_10': -2.8840491147836653}. Best is trial 0 with value: 0.3773051008529895.
[I 2026-07-30 09:27:04,600] Trial 2 finished with value: 0.3839303981289309 and parameters: {'logit_0': -1.6628428117182548, 'logit_1': -1.0691052536504664, 'logit_2': -0.35144012626371257, 'logit_3': 2.281407691144109, 'logit_4': -2.402609742733122, 'logit_5': 0.11387550730889284, 'logit_6': 0.7393165508963397, 'logit_7': -3.628396698240018, 'logit_8': 0.8603588152115069, 'logit_9': -2.6358070105016678, 'logit_10': -3.479587256117764}. Best is trial 2 with value: 0.3839303981289309.
[I 2026-07-30 09:27:05,873] Trial 3 finished with value: 0.36480940362459185 and parameters: {'logit_0': 3.591084298026666, 'logit_1': 3.725056264596475, 'logit_2': 2.467178784931689, 'logit_3': -1.5630898466130345, 'logit_4': -3.218623087948929, 'logit_5': 1.4738642120972552, 'logit_6': -0.4787800500831896, 'logit_7': -3.0236941212417694, 'logit_8': -0.03858471910983852, 'logit_9': -3.724891831078253, 'logit_10': 3.2745632166302565}. Best is trial 2 with value: 0.3839303981289309.
[I 2026-07-30 09:27:07,376] Trial 4 finished with value: 0.4081962108451341 and parameters: {'logit_0': -1.9297601471998647, 'logit_1': 1.3001782748318558, 'logit_2': -1.5063113912847124, 'logit_3': 0.1605441694224865, 'logit_4': 0.3736822347462372, 'logit_5': -2.5211643557957837, 'logit_6': 3.7566770221164685, 'logit_7': 2.2010625868889164, 'logit_8': 3.515991532513513, 'logit_9': 3.1586188034211906, 'logit_10': 0.7831998304886811}. Best is trial 4 with value: 0.4081962108451341.
[I 2026-07-30 09:27:08,783] Trial 5 finished with value: 0.3532015072417775 and parameters: {'logit_0': 3.3749938801849346, 'logit_1': -3.292059983584644, 'logit_2': -2.4321371006468384, 'logit_3': -3.6381816887156955, 'logit_4': -1.3973573538938853, 'logit_5': -0.8905816824841439, 'logit_6': -1.8292077458088327, 'logit_7': 2.6299000732154347, 'logit_8': -1.1459733864512858, 'logit_9': -1.752523922500954, 'logit_10': 0.3415686652659877}. Best is trial 4 with value: 0.4081962108451341.
[I 2026-07-30 09:27:10,112] Trial 6 finished with value: 0.3669217076265138 and parameters: {'logit_0': -2.872606200201899, 'logit_1': 2.4175758460323173, 'logit_2': -3.4035948505618334, 'logit_3': 3.8950954928041384, 'logit_4': 2.1779581543732593, 'logit_5': -2.4102745477266208, 'logit_6': -3.955823063011181, 'logit_7': 2.5236914276386733, 'logit_8': 1.654858750780937, 'logit_9': 1.8320573443278985, 'logit_10': 2.170162773487566}. Best is trial 4 with value: 0.4081962108451341.
[I 2026-07-30 09:27:11,479] Trial 7 finished with value: 0.3720850689495746 and parameters: {'logit_0': -3.407642786127277, 'logit_1': -1.1322741716458191, 'logit_2': -3.0730475237989623, 'logit_3': 2.904827407004748, 'logit_4': 0.9863850146204634, 'logit_5': -1.3528158011788065, 'logit_6': -3.491533197711811, 'logit_7': -1.5121414262747024, 'logit_8': -1.3985334237860236, 'logit_9': 1.8368494267045126, 'logit_10': 1.100459770841705}. Best is trial 4 with value: 0.4081962108451341.
[I 2026-07-30 09:27:12,851] Trial 8 finished with value: 0.3787054673496516 and parameters: {'logit_0': 3.0977019406106123, 'logit_1': -0.22228059870440564, 'logit_2': -3.0432460324935864, 'logit_3': 1.70595829778396, 'logit_4': 2.0862803889351795, 'logit_5': 0.49021758055596987, 'logit_6': 2.167737439636488, 'logit_7': -0.049635229084874055, 'logit_8': 0.18186263505595246, 'logit_9': -0.579671853131603, 'logit_10': -3.7966469860472385}. Best is trial 4 with value: 0.4081962108451341.
[I 2026-07-30 09:27:14,177] Trial 9 finished with value: 0.42671928861775243 and parameters: {'logit_0': -3.1368685840535644, 'logit_1': -3.748566514506126, 'logit_2': 1.0912832901102432, 'logit_3': -1.4851521513893866, 'logit_4': 0.06856552931762216, 'logit_5': 3.260531791408744, 'logit_6': -2.0056621668090004, 'logit_7': -0.7169366157149621, 'logit_8': 2.0444091083443894, 'logit_9': -2.1696146760670203, 'logit_10': -3.384160721369656}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:15,780] Trial 10 finished with value: 0.39534593870746565 and parameters: {'logit_0': 1.5983752813836336, 'logit_1': -3.9520225363534633, 'logit_2': 3.7562968863029287, 'logit_3': -1.2251928687470248, 'logit_4': 3.585942154213804, 'logit_5': 3.261318362260143, 'logit_6': -1.9365843791880635, 'logit_7': 1.1037740416884878, 'logit_8': -3.2242497620137636, 'logit_9': -0.9229993470990747, 'logit_10': -1.7539123660823663}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:17,227] Trial 11 finished with value: 0.4227058314501097 and parameters: {'logit_0': -2.0150121797195597, 'logit_1': 1.0170185513457526, 'logit_2': -0.42563927983813565, 'logit_3': -0.21828794673641028, 'logit_4': -0.4908264341612085, 'logit_5': -3.903679969407241, 'logit_6': 3.3141061598367223, 'logit_7': 1.2669635101900585, 'logit_8': 3.7402607119226046, 'logit_9': 3.760007008873687, 'logit_10': -1.2344500380138657}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:18,792] Trial 12 finished with value: 0.41692273323842166 and parameters: {'logit_0': 0.40308389787937404, 'logit_1': -2.749759547885435, 'logit_2': 0.5669919017831591, 'logit_3': -0.826069422121601, 'logit_4': -0.7973245803453533, 'logit_5': -3.8535019591560795, 'logit_6': 3.862579281086025, 'logit_7': -1.5421583731306967, 'logit_8': 3.994899509132413, 'logit_9': 3.7877586651539947, 'logit_10': -1.2591120395830275}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:20,158] Trial 13 finished with value: 0.4203173071431632 and parameters: {'logit_0': -3.784012978800206, 'logit_1': 1.1117789912097658, 'logit_2': 0.3206356716495351, 'logit_3': -2.5403436212004564, 'logit_4': -0.6767112325061475, 'logit_5': 3.500203774043184, 'logit_6': 1.9047867370098617, 'logit_7': 1.048674748311723, 'logit_8': 2.6930462853920196, 'logit_9': -3.6388151722018307, 'logit_10': -1.646067196456805}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:21,510] Trial 14 finished with value: 0.3689344281261022 and parameters: {'logit_0': -0.3128742871194379, 'logit_1': -1.78188803745514, 'logit_2': 1.380480082186068, 'logit_3': -0.12800422408054105, 'logit_4': 1.0504097089582167, 'logit_5': 2.0956877161811063, 'logit_6': -1.4361903171668424, 'logit_7': 3.835404734181955, 'logit_8': 2.372015247379016, 'logit_9': 0.34922161536110297, 'logit_10': -0.5873578488829336}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:22,868] Trial 15 finished with value: 0.3601892775471811 and parameters: {'logit_0': -2.5117170102156754, 'logit_1': 0.4850865473645323, 'logit_2': -0.6045376319459694, 'logit_3': 1.0346293282385242, 'logit_4': -1.4969457774897426, 'logit_5': -3.992954681282216, 'logit_6': 2.139335568797807, 'logit_7': 0.9635029458263396, 'logit_8': 2.8964173199812078, 'logit_9': -1.869687989116131, 'logit_10': -2.2870867097016294}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:24,396] Trial 16 finished with value: 0.42198233087735293 and parameters: {'logit_0': -1.2124627174761087, 'logit_1': -1.9714466506748507, 'logit_2': -0.9952406362234034, 'logit_3': -2.217190031276859, 'logit_4': 0.33439194065234645, 'logit_5': 2.298302085733763, 'logit_6': -0.8799015125849905, 'logit_7': -1.3404073125318572, 'logit_8': 1.565941098647301, 'logit_9': -2.7262828705863393, 'logit_10': -0.6641023414766348}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:25,704] Trial 17 finished with value: 0.42415751151463305 and parameters: {'logit_0': -2.636309771743096, 'logit_1': 0.017833619982771554, 'logit_2': 3.29664914394153, 'logit_3': -0.48319025283985706, 'logit_4': -3.8666910573496756, 'logit_5': 0.9820462670136019, 'logit_6': -2.6293346194475395, 'logit_7': -2.2538716936207743, 'logit_8': 3.357952938632566, 'logit_9': 3.2888410752654798, 'logit_10': -2.3665361091168364}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:27,059] Trial 18 finished with value: 0.411636248601214 and parameters: {'logit_0': 0.6108581201120318, 'logit_1': -0.30770757108801816, 'logit_2': 3.6380763975245305, 'logit_3': -3.959211695055833, 'logit_4': -3.715179310763926, 'logit_5': 1.0844063439139595, 'logit_6': -2.5263251750124596, 'logit_7': -2.599496331568082, 'logit_8': 1.8751285327145641, 'logit_9': 2.9347258726115637, 'logit_10': -2.761029714807556}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:28,431] Trial 19 finished with value: 0.4177190588152632 and parameters: {'logit_0': -3.9947980454343854, 'logit_1': -2.693271673040053, 'logit_2': 2.7492470033500154, 'logit_3': -1.9417577853977288, 'logit_4': -3.9954912927147754, 'logit_5': 2.7921306750906987, 'logit_6': -2.7329457517707714, 'logit_7': -2.6625282885137485, 'logit_8': 3.029016052664266, 'logit_9': -0.7539707160118487, 'logit_10': -2.6088091292878746}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:29,748] Trial 20 finished with value: 0.4037761324302089 and parameters: {'logit_0': -3.042285052644827, 'logit_1': 2.114154429545187, 'logit_2': 1.0379854927874592, 'logit_3': -0.683134481990503, 'logit_4': -1.654794720251871, 'logit_5': 3.9797586278477866, 'logit_6': -2.888380449604875, 'logit_7': -0.6379145843367251, 'logit_8': 2.1949529507797414, 'logit_9': 0.7490962162035326, 'logit_10': 3.9943478166701825}. Best is trial 9 with value: 0.42671928861775243.
[I 2026-07-30 09:27:31,152] Trial 21 finished with value: 0.4293698111420374 and parameters: {'logit_0': -2.199815578270998, 'logit_1': 0.7655430986812739, 'logit_2': 2.89743267820173, 'logit_3': -0.007924954829196466, 'logit_4': -0.5173280564960548, 'logit_5': -0.30205765910992777, 'logit_6': 0.8362638325707623, 'logit_7': 0.3559338517986631, 'logit_8': 3.9600935635802803, 'logit_9': 3.910532123871547, 'logit_10': -0.8513538912287222}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:32,531] Trial 22 finished with value: 0.4117791689167451 and parameters: {'logit_0': -2.6243183404291512, 'logit_1': 0.31182991985109343, 'logit_2': 2.664642347569247, 'logit_3': 0.7606275772925781, 'logit_4': 1.647261323768769, 'logit_5': -0.2816518085472849, 'logit_6': 0.5619953611207749, 'logit_7': 0.17859027657979834, 'logit_8': 3.4392875226278363, 'logit_9': 2.410793407561123, 'logit_10': -0.39291822572741064}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:33,953] Trial 23 finished with value: 0.4054519125894679 and parameters: {'logit_0': -0.7754722220034398, 'logit_1': -0.443943017261033, 'logit_2': 3.2032795366708826, 'logit_3': -1.035916556408112, 'logit_4': 3.419116185795156, 'logit_5': 1.1558465331474097, 'logit_6': 1.1546116056219704, 'logit_7': -2.1773215422346874, 'logit_8': 3.1164939227352226, 'logit_9': 2.603388829569356, 'logit_10': -2.148592332080111}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:35,274] Trial 24 finished with value: 0.42633824063577297 and parameters: {'logit_0': -2.2139220906105677, 'logit_1': -1.4125244734173026, 'logit_2': 1.8983870144071764, 'logit_3': -2.9845311798153418, 'logit_4': 2.766156493101325, 'logit_5': -0.4689748162791485, 'logit_6': -0.5695326232836062, 'logit_7': -0.7392516604175517, 'logit_8': 3.8816619805621873, 'logit_9': 3.870825963092379, 'logit_10': -3.022947886871595}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:36,622] Trial 25 finished with value: 0.42453986894549034 and parameters: {'logit_0': -1.7393394227972383, 'logit_1': -3.6676614631779154, 'logit_2': 1.604213571667926, 'logit_3': -3.033396636642336, 'logit_4': 2.527852739600922, 'logit_5': -0.5172387512315382, 'logit_6': -0.8913955618764449, 'logit_7': -0.6808844844298921, 'logit_8': 1.1296174039518525, 'logit_9': 3.9095361053958975, 'logit_10': -3.2105121476916882}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:38,025] Trial 26 finished with value: 0.41140030295938285 and parameters: {'logit_0': 1.2944103458017922, 'logit_1': -1.9369926555429626, 'logit_2': 2.0398727350006327, 'logit_3': -3.170178187636563, 'logit_4': -0.15239270875726213, 'logit_5': -1.4979738936320952, 'logit_6': 1.4246588843995092, 'logit_7': 0.18733036144233894, 'logit_8': 2.5584053538026996, 'logit_9': 1.1769173049870112, 'logit_10': 1.830186851566736}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:39,413] Trial 27 finished with value: 0.3853506063552852 and parameters: {'logit_0': -3.4257208809221904, 'logit_1': -2.7198545846058026, 'logit_2': 0.8668212878690453, 'logit_3': -2.8857458863183703, 'logit_4': 3.0155624649778607, 'logit_5': 0.4830575978006615, 'logit_6': -0.25707639081238876, 'logit_7': 1.8606991995337472, 'logit_8': 3.987973500395368, 'logit_9': -0.18502707153032738, 'logit_10': -3.9772260569246667}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:40,785] Trial 28 finished with value: 0.3879297710132572 and parameters: {'logit_0': -0.295898478472127, 'logit_1': -0.9968291932985904, 'logit_2': 2.3121036970987423, 'logit_3': -1.6012383516132196, 'logit_4': 0.8046551593999793, 'logit_5': -0.8247365082307685, 'logit_6': -1.1319229659460213, 'logit_7': 0.5567378599922032, 'logit_8': -0.07962414700457243, 'logit_9': -1.7019561974757638, 'logit_10': -1.2905730928976769}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:42,206] Trial 29 finished with value: 0.4049450363096597 and parameters: {'logit_0': -0.9519368930018606, 'logit_1': 1.7867039843460952, 'logit_2': 1.7018943091511272, 'logit_3': 0.5138751062268042, 'logit_4': 1.4010315271346783, 'logit_5': -2.0518835641698256, 'logit_6': -0.09143918453037345, 'logit_7': -0.6797311602880828, 'logit_8': -3.8248678814389345, 'logit_9': 2.358996062193562, 'logit_10': -3.1111636795484205}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:43,632] Trial 30 finished with value: 0.39907945166521985 and parameters: {'logit_0': -2.2693349638432467, 'logit_1': 3.1039226344247837, 'logit_2': 0.19685242453972174, 'logit_3': -2.0031129014176625, 'logit_4': -1.9507502960962992, 'logit_5': 1.956263370153689, 'logit_6': -2.1208767870081577, 'logit_7': -1.0145589342894692, 'logit_8': 1.2984876996040238, 'logit_9': -2.8312581483288843, 'logit_10': -3.577951932774865}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:45,027] Trial 31 finished with value: 0.4235293817008104 and parameters: {'logit_0': -1.5032269668749307, 'logit_1': -3.7275066403977712, 'logit_2': 2.095626079273052, 'logit_3': -3.3541182427718925, 'logit_4': 2.7504445976615335, 'logit_5': -0.5142616826847322, 'logit_6': -0.7196205950433008, 'logit_7': -0.25897549594226366, 'logit_8': 1.033873857764779, 'logit_9': 3.9174538562731174, 'logit_10': -3.2167068089338064}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:46,393] Trial 32 finished with value: 0.4203031824604809 and parameters: {'logit_0': -3.1157302763731187, 'logit_1': -3.3493602271526197, 'logit_2': 1.5735529611045893, 'logit_3': -2.7128608015641977, 'logit_4': 2.4960401009496014, 'logit_5': 0.11519995846503472, 'logit_6': -0.9881241452031742, 'logit_7': -0.8802236982470271, 'logit_8': 0.3371508463468169, 'logit_9': 3.204217007090229, 'logit_10': -3.1158739864394915}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:47,725] Trial 33 finished with value: 0.42586690358873813 and parameters: {'logit_0': -1.5351718867682964, 'logit_1': -3.3481150952295144, 'logit_2': 1.185056357626721, 'logit_3': -2.3286308610751663, 'logit_4': 1.7880875661539861, 'logit_5': -0.7509121051634224, 'logit_6': 0.24046254202225936, 'logit_7': -1.772331814459843, 'logit_8': -0.5196130813060535, 'logit_9': 3.5287543771618495, 'logit_10': -3.968302660798569}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:49,032] Trial 34 finished with value: 0.3905314200145081 and parameters: {'logit_0': -1.3246920959193136, 'logit_1': -3.223393824976182, 'logit_2': 1.1239215304410999, 'logit_3': -1.5811982122972283, 'logit_4': 3.8209443117141246, 'logit_5': -3.2121824149263825, 'logit_6': 0.2990215457889278, 'logit_7': -1.9382693220444587, 'logit_8': -0.6403207160573732, 'logit_9': 1.3602575014053842, 'logit_10': -3.8863473440871825}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:50,389] Trial 35 finished with value: 0.4236050399278431 and parameters: {'logit_0': -2.0364989863799434, 'logit_1': -2.2549407024305577, 'logit_2': 3.085780055194293, 'logit_3': -2.3439449983490905, 'logit_4': 1.6993954934628204, 'logit_5': -1.9342002625147146, 'logit_6': 1.0153124654518444, 'logit_7': -3.1248544761339105, 'logit_8': -2.0578276914175935, 'logit_9': 3.5049812919785066, 'logit_10': -1.9310967452743535}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:51,793] Trial 36 finished with value: 0.42404446597470313 and parameters: {'logit_0': -3.3273135272332754, 'logit_1': -1.1005959044932605, 'logit_2': 0.8514070186600071, 'logit_3': 1.2974300415633775, 'logit_4': 0.27457955017551805, 'logit_5': -1.077616240421035, 'logit_6': 0.267944078935324, 'logit_7': -3.777328824007073, 'logit_8': -0.47496644405494814, 'logit_9': 2.8866404362639235, 'logit_10': -2.8794878493773663}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:53,261] Trial 37 finished with value: 0.4223127353479253 and parameters: {'logit_0': -2.222392945021322, 'logit_1': -1.535432172782786, 'logit_2': 2.574077726401165, 'logit_3': -1.3478001772341333, 'logit_4': -1.0994045525973193, 'logit_5': 0.1819598092303642, 'logit_6': 1.624750141407921, 'logit_7': -1.1837752182522383, 'logit_8': -1.9032319052573023, 'logit_9': 2.0772675619561567, 'logit_10': 0.10909748258248825}. Best is trial 21 with value: 0.4293698111420374.
[I 2026-07-30 09:27:54,628] Trial 38 finished with value: 0.43012515152182296 and parameters: {'logit_0': -0.819622310554353, 'logit_1': 0.6310659069945745, 'logit_2': 1.9129137848807187, 'logit_3': -3.460868770513751, 'logit_4': -0.2415584929991222, 'logit_5': 0.718180783902215, 'logit_6': -0.44624048207082745, 'logit_7': 0.44887347557467494, 'logit_8': 0.5845989209998224, 'logit_9': 3.4052917506578497, 'logit_10': -3.6240709739479}. Best is trial 38 with value: 0.43012515152182296.
[I 2026-07-30 09:27:55,947] Trial 39 finished with value: 0.42805780737785937 and parameters: {'logit_0': -0.28917195400949236, 'logit_1': 0.7302678038940673, 'logit_2': 2.023129285280959, 'logit_3': -3.6762624066801686, 'logit_4': -2.772800054564598, 'logit_5': 1.8225620162910914, 'logit_6': -1.514873804825373, 'logit_7': 0.5445751740446474, 'logit_8': 0.6096959108693105, 'logit_9': 2.92504909424492, 'logit_10': -2.6399061400059676}. Best is trial 38 with value: 0.43012515152182296.

[I 2026-07-30 09:30:33,652] A new study created in memory with name: no-name-d5c12170-4bf2-4ef2-a6ed-c02a790d3d1b

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-07-30 09:30:35,425] Trial 0 finished with value: 0.3687810901573112 and parameters: {'logit_0': -1.0036790492211, 'logit_1': 3.6057144512793293, 'logit_2': 1.8559515344912407, 'logit_3': 0.7892678735762928, 'logit_4': -2.751850876460508, 'logit_5': -2.752043837310379, 'logit_6': -3.5353311026544043, 'logit_7': 2.9294091661994814, 'logit_8': 0.8089200939456704, 'logit_9': 1.664580622368364, 'logit_10': -3.8353240456335804}. Best is trial 0 with value: 0.3687810901573112.
[I 2026-07-30 09:30:37,199] Trial 1 finished with value: 0.3682594160106163 and parameters: {'logit_0': 3.7592788172959546, 'logit_1': 2.659541126403374, 'logit_2': -2.3012871145737908, 'logit_3': -2.545400262343195, 'logit_4': -2.5327639211725295, 'logit_5': -1.5660620563236982, 'logit_6': 0.19805145305790273, 'logit_7': -0.5444398508630739, 'logit_8': -1.6701668784156647, 'logit_9': 0.8948231577790358, 'logit_10': -2.8840491147836653}. Best is trial 0 with value: 0.3687810901573112.
[I 2026-07-30 09:30:38,945] Trial 2 finished with value: 0.37903242268223597 and parameters: {'logit_0': -1.6628428117182548, 'logit_1': -1.0691052536504664, 'logit_2': -0.35144012626371257, 'logit_3': 2.281407691144109, 'logit_4': -2.402609742733122, 'logit_5': 0.11387550730889284, 'logit_6': 0.7393165508963397, 'logit_7': -3.628396698240018, 'logit_8': 0.8603588152115069, 'logit_9': -2.6358070105016678, 'logit_10': -3.479587256117764}. Best is trial 2 with value: 0.37903242268223597.
[I 2026-07-30 09:30:40,703] Trial 3 finished with value: 0.3604726061277346 and parameters: {'logit_0': 3.591084298026666, 'logit_1': 3.725056264596475, 'logit_2': 2.467178784931689, 'logit_3': -1.5630898466130345, 'logit_4': -3.218623087948929, 'logit_5': 1.4738642120972552, 'logit_6': -0.4787800500831896, 'logit_7': -3.0236941212417694, 'logit_8': -0.03858471910983852, 'logit_9': -3.724891831078253, 'logit_10': 3.2745632166302565}. Best is trial 2 with value: 0.37903242268223597.
[I 2026-07-30 09:30:42,497] Trial 4 finished with value: 0.3986341077881268 and parameters: {'logit_0': -1.9297601471998647, 'logit_1': 1.3001782748318558, 'logit_2': -1.5063113912847124, 'logit_3': 0.1605441694224865, 'logit_4': 0.3736822347462372, 'logit_5': -2.5211643557957837, 'logit_6': 3.7566770221164685, 'logit_7': 2.2010625868889164, 'logit_8': 3.515991532513513, 'logit_9': 3.1586188034211906, 'logit_10': 0.7831998304886811}. Best is trial 4 with value: 0.3986341077881268.
[I 2026-07-30 09:30:44,290] Trial 5 finished with value: 0.3483290145097457 and parameters: {'logit_0': 3.3749938801849346, 'logit_1': -3.292059983584644, 'logit_2': -2.4321371006468384, 'logit_3': -3.6381816887156955, 'logit_4': -1.3973573538938853, 'logit_5': -0.8905816824841439, 'logit_6': -1.8292077458088327, 'logit_7': 2.6299000732154347, 'logit_8': -1.1459733864512858, 'logit_9': -1.752523922500954, 'logit_10': 0.3415686652659877}. Best is trial 4 with value: 0.3986341077881268.
[I 2026-07-30 09:30:46,295] Trial 6 finished with value: 0.36483826106676936 and parameters: {'logit_0': -2.872606200201899, 'logit_1': 2.4175758460323173, 'logit_2': -3.4035948505618334, 'logit_3': 3.8950954928041384, 'logit_4': 2.1779581543732593, 'logit_5': -2.4102745477266208, 'logit_6': -3.955823063011181, 'logit_7': 2.5236914276386733, 'logit_8': 1.654858750780937, 'logit_9': 1.8320573443278985, 'logit_10': 2.170162773487566}. Best is trial 4 with value: 0.3986341077881268.
[I 2026-07-30 09:30:48,356] Trial 7 finished with value: 0.37154488026303056 and parameters: {'logit_0': -3.407642786127277, 'logit_1': -1.1322741716458191, 'logit_2': -3.0730475237989623, 'logit_3': 2.904827407004748, 'logit_4': 0.9863850146204634, 'logit_5': -1.3528158011788065, 'logit_6': -3.491533197711811, 'logit_7': -1.5121414262747024, 'logit_8': -1.3985334237860236, 'logit_9': 1.8368494267045126, 'logit_10': 1.100459770841705}. Best is trial 4 with value: 0.3986341077881268.
[I 2026-07-30 09:30:50,150] Trial 8 finished with value: 0.37386842151896127 and parameters: {'logit_0': 3.0977019406106123, 'logit_1': -0.22228059870440564, 'logit_2': -3.0432460324935864, 'logit_3': 1.70595829778396, 'logit_4': 2.0862803889351795, 'logit_5': 0.49021758055596987, 'logit_6': 2.167737439636488, 'logit_7': -0.049635229084874055, 'logit_8': 0.18186263505595246, 'logit_9': -0.579671853131603, 'logit_10': -3.7966469860472385}. Best is trial 4 with value: 0.3986341077881268.
[I 2026-07-30 09:30:51,935] Trial 9 finished with value: 0.41080784062027487 and parameters: {'logit_0': -3.1368685840535644, 'logit_1': -3.748566514506126, 'logit_2': 1.0912832901102432, 'logit_3': -1.4851521513893866, 'logit_4': 0.06856552931762216, 'logit_5': 3.260531791408744, 'logit_6': -2.0056621668090004, 'logit_7': -0.7169366157149621, 'logit_8': 2.0444091083443894, 'logit_9': -2.1696146760670203, 'logit_10': -3.384160721369656}. Best is trial 9 with value: 0.41080784062027487.
[I 2026-07-30 09:30:53,755] Trial 10 finished with value: 0.38226549252353004 and parameters: {'logit_0': 1.5983752813836336, 'logit_1': -3.9520225363534633, 'logit_2': 3.7562968863029287, 'logit_3': -1.2251928687470248, 'logit_4': 3.585942154213804, 'logit_5': 3.261318362260143, 'logit_6': -1.9365843791880635, 'logit_7': 1.1037740416884878, 'logit_8': -3.2242497620137636, 'logit_9': -0.9229993470990747, 'logit_10': -1.7539123660823663}. Best is trial 9 with value: 0.41080784062027487.
[I 2026-07-30 09:30:55,487] Trial 11 finished with value: 0.4129259162438229 and parameters: {'logit_0': -2.0150121797195597, 'logit_1': 1.0170185513457526, 'logit_2': -0.42563927983813565, 'logit_3': -0.21828794673641028, 'logit_4': -0.4908264341612085, 'logit_5': -3.903679969407241, 'logit_6': 3.3141061598367223, 'logit_7': 1.2669635101900585, 'logit_8': 3.7402607119226046, 'logit_9': 3.760007008873687, 'logit_10': -1.2344500380138657}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:30:57,217] Trial 12 finished with value: 0.4074012978401257 and parameters: {'logit_0': 0.40308389787937404, 'logit_1': -2.749759547885435, 'logit_2': 0.5669919017831591, 'logit_3': -0.826069422121601, 'logit_4': -0.7973245803453533, 'logit_5': -3.8535019591560795, 'logit_6': 3.862579281086025, 'logit_7': -1.5421583731306967, 'logit_8': 3.994899509132413, 'logit_9': 3.7877586651539947, 'logit_10': -1.2591120395830275}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:30:58,976] Trial 13 finished with value: 0.40757739843200796 and parameters: {'logit_0': -3.784012978800206, 'logit_1': 1.1117789912097658, 'logit_2': 0.3206356716495351, 'logit_3': -2.5403436212004564, 'logit_4': -0.6767112325061475, 'logit_5': 3.500203774043184, 'logit_6': 1.9047867370098617, 'logit_7': 1.048674748311723, 'logit_8': 2.6930462853920196, 'logit_9': -3.6388151722018307, 'logit_10': -1.646067196456805}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:00,652] Trial 14 finished with value: 0.3619226963050679 and parameters: {'logit_0': -0.3128742871194379, 'logit_1': -1.78188803745514, 'logit_2': 1.380480082186068, 'logit_3': -0.12800422408054105, 'logit_4': 1.0504097089582167, 'logit_5': 2.0956877161811063, 'logit_6': -1.4361903171668424, 'logit_7': 3.835404734181955, 'logit_8': 2.372015247379016, 'logit_9': 0.34922161536110297, 'logit_10': -0.5873578488829336}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:02,464] Trial 15 finished with value: 0.35346853587357774 and parameters: {'logit_0': -2.5117170102156754, 'logit_1': 0.4850865473645323, 'logit_2': -0.6045376319459694, 'logit_3': 1.0346293282385242, 'logit_4': -1.4969457774897426, 'logit_5': -3.992954681282216, 'logit_6': 2.139335568797807, 'logit_7': 0.9635029458263396, 'logit_8': 2.8964173199812078, 'logit_9': -1.869687989116131, 'logit_10': -2.2870867097016294}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:04,129] Trial 16 finished with value: 0.4080484059786066 and parameters: {'logit_0': -1.2124627174761087, 'logit_1': -1.9714466506748507, 'logit_2': -0.9952406362234034, 'logit_3': -2.217190031276859, 'logit_4': 0.33439194065234645, 'logit_5': 2.298302085733763, 'logit_6': -0.8799015125849905, 'logit_7': -1.3404073125318572, 'logit_8': 1.565941098647301, 'logit_9': -2.7262828705863393, 'logit_10': -0.6641023414766348}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:05,890] Trial 17 finished with value: 0.4087896720570445 and parameters: {'logit_0': -2.636309771743096, 'logit_1': 0.017833619982771554, 'logit_2': 3.29664914394153, 'logit_3': -0.48319025283985706, 'logit_4': -3.8666910573496756, 'logit_5': 0.9820462670136019, 'logit_6': -2.6293346194475395, 'logit_7': -2.2538716936207743, 'logit_8': 3.357952938632566, 'logit_9': 3.2888410752654798, 'logit_10': -2.3665361091168364}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:07,678] Trial 18 finished with value: 0.3843581731184526 and parameters: {'logit_0': 0.6108581201120318, 'logit_1': 1.9229363501856211, 'logit_2': 1.0302746108775214, 'logit_3': -3.959211695055833, 'logit_4': 1.8658891376901634, 'logit_5': -0.677453184355925, 'logit_6': 1.3025013325818935, 'logit_7': 0.44800960807489054, 'logit_8': 1.9204522259824115, 'logit_9': -1.100048803375659, 'logit_10': -2.9828492639290225}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:09,424] Trial 19 finished with value: 0.39148434102042245 and parameters: {'logit_0': -3.9947980454343854, 'logit_1': -0.5831119117922414, 'logit_2': 2.343958396287772, 'logit_3': -1.9417577853977288, 'logit_4': -0.5407480424297556, 'logit_5': 2.7072387100912256, 'logit_6': 2.9022906586250574, 'logit_7': -0.5440202693515337, 'logit_8': 3.8993485661615193, 'logit_9': 0.8324336274516104, 'logit_10': -0.29213814356211243}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:11,144] Trial 20 finished with value: 0.39446386232895725 and parameters: {'logit_0': -0.5160667465281981, 'logit_1': 0.5409371758455731, 'logit_2': -1.6594421957534737, 'logit_3': 0.6617860929695061, 'logit_4': 3.0600710511183156, 'logit_5': 3.9797586278477866, 'logit_6': 0.0997791320010526, 'logit_7': 1.8219004293696863, 'logit_8': 2.3953740568419057, 'logit_9': 2.6144821197132977, 'logit_10': 3.9943478166701825}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:12,930] Trial 21 finished with value: 0.4100691382250925 and parameters: {'logit_0': -2.7370398408791976, 'logit_1': 0.1874445230758669, 'logit_2': 3.8639341978184714, 'logit_3': -0.6344444217632753, 'logit_4': -3.6113865415097557, 'logit_5': 1.4462754064557017, 'logit_6': -2.520264990280528, 'logit_7': -2.4899824171453977, 'logit_8': 3.197929198683117, 'logit_9': 3.910532123871547, 'logit_10': -2.4320625671985328}. Best is trial 11 with value: 0.4129259162438229.
[I 2026-07-30 09:31:14,740] Trial 22 finished with value: 0.41640662903925146 and parameters: {'logit_0': -2.024522647817154, 'logit_1': 1.003233375831329, 'logit_2': 3.152203102937939, 'logit_3': -0.5693516316025812, 'logit_4': -1.5331002395940605, 'logit_5': 1.479570925214915, 'logit_6': -2.7568671062241705, 'logit_7': -2.4838474900943153, 'logit_8': 3.00560914991303, 'logit_9': 3.91954007511872, 'logit_10': -2.602613379074776}. Best is trial 22 with value: 0.41640662903925146.
[I 2026-07-30 09:31:16,471] Trial 23 finished with value: 0.4084528546927289 and parameters: {'logit_0': -1.9391539232525017, 'logit_1': 1.5658944920128137, 'logit_2': 2.5880122137661195, 'logit_3': -1.1963266151024299, 'logit_4': -1.7260310188620875, 'logit_5': 2.8734455852941867, 'logit_6': -2.694834972761181, 'logit_7': -0.7689160427099786, 'logit_8': 1.251397780025715, 'logit_9': 2.607413683044612, 'logit_10': -1.0460821358270123}. Best is trial 22 with value: 0.41640662903925146.
[I 2026-07-30 09:31:18,266] Trial 24 finished with value: 0.4030416026754355 and parameters: {'logit_0': -3.248968573581153, 'logit_1': 2.916402954149632, 'logit_2': 1.0014316071909621, 'logit_3': -2.9845311798153418, 'logit_4': 0.020410973443883346, 'logit_5': 1.8076304568789967, 'logit_6': -1.4419326831328532, 'logit_7': -3.8714409179596494, 'logit_8': 2.2404248605277823, 'logit_9': 2.6525211660535692, 'logit_10': -3.0528045058247213}. Best is trial 22 with value: 0.41640662903925146.
[I 2026-07-30 09:31:20,008] Trial 25 finished with value: 0.38550374332519294 and parameters: {'logit_0': -2.12960342705055, 'logit_1': 0.7539049888630586, 'logit_2': 0.09383826192090583, 'logit_3': 0.13409108083839938, 'logit_4': -1.8873952264721021, 'logit_5': 0.8050762960446916, 'logit_6': -0.6570178622241467, 'logit_7': 0.1779765966316822, 'logit_8': 2.9666847506829805, 'logit_9': -0.11098671169999585, 'logit_10': -1.905446290769143}. Best is trial 22 with value: 0.41640662903925146.
[I 2026-07-30 09:31:21,768] Trial 26 finished with value: 0.41521722908446246 and parameters: {'logit_0': -0.9236600667721466, 'logit_1': 1.9196795200068975, 'logit_2': 3.0271719408703133, 'logit_3': -1.642684016871278, 'logit_4': 0.9219579501670259, 'logit_5': -0.26877036777828067, 'logit_6': -3.1745659973357796, 'logit_7': -2.4006581512381757, 'logit_8': 3.406099517038866, 'logit_9': 3.9716386555886944, 'logit_10': -3.2683578275123004}. Best is trial 22 with value: 0.41640662903925146.
[I 2026-07-30 09:31:23,576] Trial 27 finished with value: 0.40187791257503963 and parameters: {'logit_0': -1.0243972534989756, 'logit_1': 3.0125831787017052, 'logit_2': 2.8419021454303044, 'logit_3': 1.2380779616141937, 'logit_4': 1.1943964028307272, 'logit_5': -0.3128397591414056, 'logit_6': -3.224369983650397, 'logit_7': -2.323174418287013, 'logit_8': 3.987973500395368, 'logit_9': 3.3986967129448704, 'logit_10': -1.4295568109722059}. Best is trial 22 with value: 0.41640662903925146.
[I 2026-07-30 09:31:25,395] Trial 28 finished with value: 0.4201142151404564 and parameters: {'logit_0': 1.4895237044592198, 'logit_1': 1.9199354211061879, 'logit_2': 1.7539358026536742, 'logit_3': -3.1661365652378026, 'logit_4': -0.8734025803417984, 'logit_5': -3.24090992546314, 'logit_6': 3.0110077294317197, 'logit_7': -3.012122704163064, 'logit_8': -3.079842091106401, 'logit_9': 3.9500767070313785, 'logit_10': -2.5210325634415707}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:27,092] Trial 29 finished with value: 0.38673456308729615 and parameters: {'logit_0': 1.4742466608011509, 'logit_1': 1.8277625120403582, 'logit_2': 1.9529513562463436, 'logit_3': -3.223927133895094, 'logit_4': -2.860598921231519, 'logit_5': -3.003582526996694, 'logit_6': -3.989088053014095, 'logit_7': -3.123058967291525, 'logit_8': -3.8248678814389345, 'logit_9': 2.310408030374097, 'logit_10': -3.7369315280307887}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:28,866] Trial 30 finished with value: 0.3710762044456809 and parameters: {'logit_0': 2.150883711323689, 'logit_1': 3.2963598036421446, 'logit_2': 3.188975016698632, 'logit_3': -2.9423326236544702, 'logit_4': -1.2871139656491377, 'logit_5': -1.892973953798485, 'logit_6': -3.114641099029556, 'logit_7': -3.028125801390109, 'logit_8': -2.98494139773354, 'logit_9': 1.3144780215811127, 'logit_10': -2.6031442278499366}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:30,617] Trial 31 finished with value: 0.4143105817317424 and parameters: {'logit_0': -0.5659684494407338, 'logit_1': 2.0846899465122215, 'logit_2': 3.2774774749240985, 'logit_3': 0.38457223679610864, 'logit_4': -0.47316110487225327, 'logit_5': -3.212208900837911, 'logit_6': 2.851580355856298, 'logit_7': -2.1009172983330853, 'logit_8': -2.404212309753146, 'logit_9': 3.9194043096076996, 'logit_10': -2.11930512948169}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:32,286] Trial 32 finished with value: 0.4118372904765295 and parameters: {'logit_0': 0.518618251571257, 'logit_1': 2.251584395210345, 'logit_2': 1.8209062617318037, 'logit_3': -1.9041404093874792, 'logit_4': -2.0913141171909992, 'logit_5': -3.2238901994087823, 'logit_6': 2.796120642661666, 'logit_7': -1.758771230900419, 'logit_8': -2.031453749182333, 'logit_9': 3.184129316749141, 'logit_10': -3.1297078189361365}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:34,012] Trial 33 finished with value: 0.4058962509846378 and parameters: {'logit_0': -0.5232249595971379, 'logit_1': 2.1114330795960674, 'logit_2': 3.3545609708863244, 'logit_3': -1.0673696881323511, 'logit_4': -0.9584550379581246, 'logit_5': -3.3603798182728153, 'logit_6': 0.7884037422275112, 'logit_7': -3.2803802489455993, 'logit_8': -2.4041103560659387, 'logit_9': 3.8978106288006473, 'logit_10': -3.9586893484110286}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:35,766] Trial 34 finished with value: 0.40974613391698517 and parameters: {'logit_0': -1.4134381663194802, 'logit_1': 1.5534507758352982, 'logit_2': 1.9053559082945133, 'logit_3': 0.5505415989451641, 'logit_4': 0.575425471936232, 'logit_5': -1.993717322508906, 'logit_6': 1.4898792028777907, 'logit_7': -2.5208096195575127, 'logit_8': -0.6555896499024301, 'logit_9': 2.871347342832027, 'logit_10': -2.121874245521482}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:37,514] Trial 35 finished with value: 0.38966998822634435 and parameters: {'logit_0': 0.0455021832500746, 'logit_1': 2.629065522905386, 'logit_2': 2.8204036179592316, 'logit_3': 1.805956093272742, 'logit_4': -0.19827604481993255, 'logit_5': 0.02829259010442564, 'logit_6': 2.515614921434353, 'logit_7': -3.5573655060308993, 'logit_8': -3.9438664270100876, 'logit_9': 2.063468636398624, 'logit_10': -2.7293158903487127}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:39,345] Trial 36 finished with value: 0.385964838437535 and parameters: {'logit_0': 1.1298250333550508, 'logit_1': 3.7731622119151504, 'logit_2': 3.9552422537048515, 'logit_3': -2.54950045932331, 'logit_4': -2.3778008646644655, 'logit_5': -2.2108978874325595, 'logit_6': 0.9765035011761962, 'logit_7': -1.9666152401703898, 'logit_8': -2.368412481926688, 'logit_9': 3.373328228736719, 'logit_10': -3.3136578910002283}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:41,260] Trial 37 finished with value: 0.4101606400102171 and parameters: {'logit_0': 2.468086339472527, 'logit_1': 1.5506112061014212, 'logit_2': 2.3349542589102112, 'logit_3': -1.734286631617022, 'logit_4': 1.6681261514014767, 'logit_5': -1.1733697614643228, 'logit_6': 3.330163312785655, 'logit_7': -2.759865073899933, 'logit_8': -3.1495357041888887, 'logit_9': 3.4949765647576316, 'logit_10': 1.655950138074917}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:42,987] Trial 38 finished with value: 0.3899072498157525 and parameters: {'logit_0': -0.819622310554353, 'logit_1': 2.575246864970572, 'logit_2': 3.436581963823278, 'logit_3': 0.3904881166823651, 'logit_4': 0.5089801688594457, 'logit_5': -2.9469859847854956, 'logit_6': -0.20887354793507384, 'logit_7': -3.4495948520158066, 'logit_8': 0.20441631583814157, 'logit_9': 2.9957899806419928, 'logit_10': 0.19591685968064088}. Best is trial 28 with value: 0.4201142151404564.
[I 2026-07-30 09:31:44,809] Trial 39 finished with value: 0.3852565510635092 and parameters: {'logit_0': -1.3961866741696909, 'logit_1': 3.4208612932397804, 'logit_2': 2.9388906602780116, 'logit_3': -3.334082019649127, 'logit_4': -1.1360094493742343, 'logit_5': -3.4803242278083255, 'logit_6': 3.47913718592271, 'logit_7': -3.978074228296909, 'logit_8': -0.7556011908142837, 'logit_9': 1.2108746958192422, 'logit_10': -3.5109432701770427}. Best is trial 28 with value: 0.4201142151404564.

[I 2026-07-30 09:34:59,841] A new study created in memory with name: no-name-72f5fc99-a3b3-4d63-a3c3-35aba2172107

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-07-30 09:35:02,044] Trial 0 finished with value: 0.4263533257232825 and parameters: {'logit_0': -1.0036790492211, 'logit_1': 3.6057144512793293, 'logit_2': 1.8559515344912407, 'logit_3': 0.7892678735762928, 'logit_4': -2.751850876460508, 'logit_5': -2.752043837310379, 'logit_6': -3.5353311026544043, 'logit_7': 2.9294091661994814, 'logit_8': 0.8089200939456704, 'logit_9': 1.664580622368364, 'logit_10': -3.8353240456335804}. Best is trial 0 with value: 0.4263533257232825.
[I 2026-07-30 09:35:04,177] Trial 1 finished with value: 0.42991694224019655 and parameters: {'logit_0': 3.7592788172959546, 'logit_1': 2.659541126403374, 'logit_2': -2.3012871145737908, 'logit_3': -2.545400262343195, 'logit_4': -2.5327639211725295, 'logit_5': -1.5660620563236982, 'logit_6': 0.19805145305790273, 'logit_7': -0.5444398508630739, 'logit_8': -1.6701668784156647, 'logit_9': 0.8948231577790358, 'logit_10': -2.8840491147836653}. Best is trial 1 with value: 0.42991694224019655.
[I 2026-07-30 09:35:06,362] Trial 2 finished with value: 0.4331494019024779 and parameters: {'logit_0': -1.6628428117182548, 'logit_1': -1.0691052536504664, 'logit_2': -0.35144012626371257, 'logit_3': 2.281407691144109, 'logit_4': -2.402609742733122, 'logit_5': 0.11387550730889284, 'logit_6': 0.7393165508963397, 'logit_7': -3.628396698240018, 'logit_8': 0.8603588152115069, 'logit_9': -2.6358070105016678, 'logit_10': -3.479587256117764}. Best is trial 2 with value: 0.4331494019024779.
[I 2026-07-30 09:35:08,509] Trial 3 finished with value: 0.4137981680602072 and parameters: {'logit_0': 3.591084298026666, 'logit_1': 3.725056264596475, 'logit_2': 2.467178784931689, 'logit_3': -1.5630898466130345, 'logit_4': -3.218623087948929, 'logit_5': 1.4738642120972552, 'logit_6': -0.4787800500831896, 'logit_7': -3.0236941212417694, 'logit_8': -0.03858471910983852, 'logit_9': -3.724891831078253, 'logit_10': 3.2745632166302565}. Best is trial 2 with value: 0.4331494019024779.
[I 2026-07-30 09:35:10,641] Trial 4 finished with value: 0.43829880787046016 and parameters: {'logit_0': -1.9297601471998647, 'logit_1': 1.3001782748318558, 'logit_2': -1.5063113912847124, 'logit_3': 0.1605441694224865, 'logit_4': 0.3736822347462372, 'logit_5': -2.5211643557957837, 'logit_6': 3.7566770221164685, 'logit_7': 2.2010625868889164, 'logit_8': 3.515991532513513, 'logit_9': 3.1586188034211906, 'logit_10': 0.7831998304886811}. Best is trial 4 with value: 0.43829880787046016.
[I 2026-07-30 09:35:12,814] Trial 5 finished with value: 0.3985445953716817 and parameters: {'logit_0': 3.3749938801849346, 'logit_1': -3.292059983584644, 'logit_2': -2.4321371006468384, 'logit_3': -3.6381816887156955, 'logit_4': -1.3973573538938853, 'logit_5': -0.8905816824841439, 'logit_6': -1.8292077458088327, 'logit_7': 2.6299000732154347, 'logit_8': -1.1459733864512858, 'logit_9': -1.752523922500954, 'logit_10': 0.3415686652659877}. Best is trial 4 with value: 0.43829880787046016.
[I 2026-07-30 09:35:14,900] Trial 6 finished with value: 0.4209061115569523 and parameters: {'logit_0': -2.872606200201899, 'logit_1': 2.4175758460323173, 'logit_2': -3.4035948505618334, 'logit_3': 3.8950954928041384, 'logit_4': 2.1779581543732593, 'logit_5': -2.4102745477266208, 'logit_6': -3.955823063011181, 'logit_7': 2.5236914276386733, 'logit_8': 1.654858750780937, 'logit_9': 1.8320573443278985, 'logit_10': 2.170162773487566}. Best is trial 4 with value: 0.43829880787046016.
[I 2026-07-30 09:35:17,095] Trial 7 finished with value: 0.4249562816854126 and parameters: {'logit_0': -3.407642786127277, 'logit_1': -1.1322741716458191, 'logit_2': -3.0730475237989623, 'logit_3': 2.904827407004748, 'logit_4': 0.9863850146204634, 'logit_5': -1.3528158011788065, 'logit_6': -3.491533197711811, 'logit_7': -1.5121414262747024, 'logit_8': -1.3985334237860236, 'logit_9': 1.8368494267045126, 'logit_10': 1.100459770841705}. Best is trial 4 with value: 0.43829880787046016.
[I 2026-07-30 09:35:19,312] Trial 8 finished with value: 0.4318080325224974 and parameters: {'logit_0': 3.0977019406106123, 'logit_1': -0.22228059870440564, 'logit_2': -3.0432460324935864, 'logit_3': 1.70595829778396, 'logit_4': 2.0862803889351795, 'logit_5': 0.49021758055596987, 'logit_6': 2.167737439636488, 'logit_7': -0.049635229084874055, 'logit_8': 0.18186263505595246, 'logit_9': -0.579671853131603, 'logit_10': -3.7966469860472385}. Best is trial 4 with value: 0.43829880787046016.
[I 2026-07-30 09:35:21,513] Trial 9 finished with value: 0.4590129422501954 and parameters: {'logit_0': -3.1368685840535644, 'logit_1': -3.748566514506126, 'logit_2': 1.0912832901102432, 'logit_3': -1.4851521513893866, 'logit_4': 0.06856552931762216, 'logit_5': 3.260531791408744, 'logit_6': -2.0056621668090004, 'logit_7': -0.7169366157149621, 'logit_8': 2.0444091083443894, 'logit_9': -2.1696146760670203, 'logit_10': -3.384160721369656}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:23,968] Trial 10 finished with value: 0.43312587061156277 and parameters: {'logit_0': 1.5983752813836336, 'logit_1': -3.9520225363534633, 'logit_2': 3.7562968863029287, 'logit_3': -1.2251928687470248, 'logit_4': 3.585942154213804, 'logit_5': 3.261318362260143, 'logit_6': -1.9365843791880635, 'logit_7': 1.1037740416884878, 'logit_8': -3.2242497620137636, 'logit_9': -0.9229993470990747, 'logit_10': -1.7539123660823663}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:26,195] Trial 11 finished with value: 0.4505642921728125 and parameters: {'logit_0': -2.0150121797195597, 'logit_1': 1.0170185513457526, 'logit_2': -0.42563927983813565, 'logit_3': -0.21828794673641028, 'logit_4': -0.4908264341612085, 'logit_5': -3.903679969407241, 'logit_6': 3.3141061598367223, 'logit_7': 1.2669635101900585, 'logit_8': 3.7402607119226046, 'logit_9': 3.760007008873687, 'logit_10': -1.2344500380138657}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:28,423] Trial 12 finished with value: 0.443494306574785 and parameters: {'logit_0': 0.40308389787937404, 'logit_1': -2.749759547885435, 'logit_2': 0.5669919017831591, 'logit_3': -0.826069422121601, 'logit_4': -0.7973245803453533, 'logit_5': -3.8535019591560795, 'logit_6': 3.862579281086025, 'logit_7': -1.5421583731306967, 'logit_8': 3.994899509132413, 'logit_9': 3.7877586651539947, 'logit_10': -1.2591120395830275}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:30,688] Trial 13 finished with value: 0.4548158749836972 and parameters: {'logit_0': -3.784012978800206, 'logit_1': 1.1117789912097658, 'logit_2': 0.3206356716495351, 'logit_3': -2.5403436212004564, 'logit_4': -0.6767112325061475, 'logit_5': 3.500203774043184, 'logit_6': 1.9047867370098617, 'logit_7': 1.048674748311723, 'logit_8': 2.6930462853920196, 'logit_9': -3.6388151722018307, 'logit_10': -1.646067196456805}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:32,847] Trial 14 finished with value: 0.43596958926989554 and parameters: {'logit_0': -3.6183947709598754, 'logit_1': -1.78188803745514, 'logit_2': 1.2539531814922682, 'logit_3': -2.6065491422091682, 'logit_4': 1.0504097089582167, 'logit_5': 3.7452951586646517, 'logit_6': 1.715614374314607, 'logit_7': 3.835404734181955, 'logit_8': 2.372015247379016, 'logit_9': -3.64581415820243, 'logit_10': -2.378968845621242}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:34,956] Trial 15 finished with value: 0.44475804669026114 and parameters: {'logit_0': -3.928588818062126, 'logit_1': 0.4850865473645323, 'logit_2': 2.6885825182152203, 'logit_3': -3.9550240814820627, 'logit_4': -1.397708465630707, 'logit_5': 2.6353228516127247, 'logit_6': -1.2675992405160605, 'logit_7': 0.9611912622764611, 'logit_8': 2.4597183184209275, 'logit_9': -2.2212291447909775, 'logit_10': -0.5697262487224566}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:37,086] Trial 16 finished with value: 0.4450276153741674 and parameters: {'logit_0': -0.038819415833318605, 'logit_1': 1.890612978823162, 'logit_2': 0.5590334384180886, 'logit_3': -2.2460744075275523, 'logit_4': 0.23903385896424933, 'logit_5': 1.978893750902007, 'logit_6': 1.8392227245646975, 'logit_7': -1.114566423955547, 'logit_8': 2.5895703081077803, 'logit_9': -2.9177043058025394, 'logit_10': -2.3290283819495468}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:39,301] Trial 17 finished with value: 0.4521814332375766 and parameters: {'logit_0': -2.7363895995195495, 'logit_1': -0.5041220468071987, 'logit_2': -0.7051289056270258, 'logit_3': -3.192829982413519, 'logit_4': -3.8857236520885934, 'logit_5': 3.919272370173414, 'logit_6': -2.6293346194475395, 'logit_7': -2.2538716936207743, 'logit_8': 1.7212241327009772, 'logit_9': -1.428764088653185, 'logit_10': -0.45156160476928076}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:41,409] Trial 18 finished with value: 0.44306908068916584 and parameters: {'logit_0': -0.6547673417434066, 'logit_1': -1.7251185051822118, 'logit_2': 1.112121844948994, 'logit_3': -1.7259472061054757, 'logit_4': 1.8658891376901634, 'logit_5': 1.499158644306137, 'logit_6': -0.7666499661106989, 'logit_7': 0.2670046182156849, 'logit_8': 2.970372129988644, 'logit_9': 0.1577623146319726, 'logit_10': -2.890203548554908}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:43,531] Trial 19 finished with value: 0.4449515450915037 and parameters: {'logit_0': -2.8282941616348816, 'logit_1': -2.693271673040053, 'logit_2': -1.546118293058674, 'logit_3': -0.5858775572673709, 'logit_4': -1.807840793408557, 'logit_5': 2.7072387100912256, 'logit_6': 2.7067911858151392, 'logit_7': 0.3868808161738966, 'logit_8': 1.7380460114216107, 'logit_9': -3.370346634091296, 'logit_10': -1.7168602786775424}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:45,692] Trial 20 finished with value: 0.3794413259101186 and parameters: {'logit_0': 1.8741683950697539, 'logit_1': 0.33633135981174855, 'logit_2': 3.6397136280607105, 'logit_3': 0.6617860929695061, 'logit_4': -0.5603528257680093, 'logit_5': 0.9054394669364481, 'logit_6': 0.4255783683637273, 'logit_7': 1.7115093134553854, 'logit_8': 0.9938770629515279, 'logit_9': -2.041735014831984, 'logit_10': 3.9943478166701825}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:47,814] Trial 21 finished with value: 0.4519069691112303 and parameters: {'logit_0': -2.776382897858349, 'logit_1': -0.3569912058156908, 'logit_2': -0.955625900127999, 'logit_3': -3.383075977123406, 'logit_4': -3.6295753692519206, 'logit_5': 3.910332251353758, 'logit_6': -2.520264990280528, 'logit_7': -2.4899824171453977, 'logit_8': 1.8554665744319627, 'logit_9': -1.3463828934305, 'logit_10': -0.5192764414991355}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:49,939] Trial 22 finished with value: 0.4538925540177668 and parameters: {'logit_0': -2.3558411961231602, 'logit_1': 1.0886656015157474, 'logit_2': 0.21639757226566342, 'logit_3': -3.0645536402137523, 'logit_4': -3.9760604977639145, 'logit_5': 2.8945716438803935, 'logit_6': -2.815658122510733, 'logit_7': -2.396953958075231, 'logit_8': 2.906563974553248, 'logit_9': -2.700779876307698, 'logit_10': -0.39291822572741064}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:52,095] Trial 23 finished with value: 0.4480739001908706 and parameters: {'logit_0': -3.991809152336897, 'logit_1': 1.1995563217335794, 'logit_2': 0.25770246312565936, 'logit_3': -2.218082812687271, 'logit_4': 2.933923679887574, 'logit_5': 2.8303000822643933, 'logit_6': 1.146334344653988, 'logit_7': -0.6552466626522646, 'logit_8': 3.1164939227352226, 'logit_9': -2.8229126940392, 'logit_10': -2.539249043770985}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:54,285] Trial 24 finished with value: 0.44149319598001197 and parameters: {'logit_0': -2.2386885425038154, 'logit_1': 1.7489676271625099, 'logit_2': 1.3550150726986983, 'logit_3': -2.9845311798153418, 'logit_4': 0.9143220761208468, 'logit_5': 2.2092657036208623, 'logit_6': -2.824089514602777, 'logit_7': -3.8634353966878123, 'logit_8': 3.1759600708488973, 'logit_9': -3.9777273572772853, 'logit_10': 1.5927396226494581}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:56,391] Trial 25 finished with value: 0.4542430627256493 and parameters: {'logit_0': -3.2711205994296613, 'logit_1': 2.9467803788276044, 'logit_2': 0.11167675659751358, 'logit_3': -1.877213191233504, 'logit_4': -1.7096634648736826, 'logit_5': 3.184147325983414, 'logit_6': -1.597873515622167, 'logit_7': -1.9350155752597271, 'logit_8': 2.359280275867497, 'logit_9': -3.1562245422429, 'logit_10': -1.4728713213600946}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:35:58,508] Trial 26 finished with value: 0.4493515409794079 and parameters: {'logit_0': -1.0821281991279483, 'logit_1': 2.8462906516408344, 'logit_2': 2.0398727350006327, 'logit_3': -1.725462756417902, 'logit_4': -1.661879129461227, 'logit_5': 3.2634584500338377, 'logit_6': -1.241483352803094, 'logit_7': -0.3382036609108141, 'logit_8': -0.20238465508840608, 'logit_9': -0.13135616221928315, 'logit_10': -1.652482338955613}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:00,605] Trial 27 finished with value: 0.44784604973515596 and parameters: {'logit_0': -3.2852095705755326, 'logit_1': 3.2034064008831575, 'logit_2': 0.9290219588965452, 'logit_3': -1.1304582877959823, 'logit_4': -0.8211264219877945, 'logit_5': 2.0350720729165133, 'logit_6': -0.25707639081238876, 'logit_7': -1.2366168628571435, 'logit_8': 2.1714771762799683, 'logit_9': -3.2948580367177676, 'logit_10': -3.1710585025330666}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:02,735] Trial 28 finished with value: 0.4440657624752961 and parameters: {'logit_0': -3.2474624443386895, 'logit_1': 2.0583288204271413, 'logit_2': -1.3089547017310128, 'logit_3': -2.081111489244247, 'logit_4': -0.08792185226843163, 'logit_5': 1.3731784625818524, 'logit_6': -1.804561313205518, 'logit_7': 0.7025109336177499, 'logit_8': 1.2057484671204948, 'logit_9': -2.321601924588625, 'logit_10': -1.2905730928976769}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:04,883] Trial 29 finished with value: 0.43380924080875016 and parameters: {'logit_0': -1.5162167442679686, 'logit_1': 3.3584915003545146, 'logit_2': 3.002998682862058, 'logit_3': 0.3171712813587151, 'logit_4': -1.9154877230218084, 'logit_5': 3.302806726929713, 'logit_6': -1.0626209082273728, 'logit_7': 3.4689307864848997, 'logit_8': 0.4838032856174721, 'logit_9': -3.2319478835238216, 'logit_10': -2.1350700044057263}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:07,020] Trial 30 finished with value: 0.44522519492488105 and parameters: {'logit_0': -1.0963234952058838, 'logit_1': 3.9356517229059857, 'logit_2': 1.932902328212946, 'logit_3': -0.647469635563946, 'logit_4': -3.0742226008349958, 'logit_5': 2.3398927811307546, 'logit_6': 0.973546297093867, 'logit_7': -2.026102293362807, 'logit_8': 1.2984876996040238, 'logit_9': -3.9786563097817496, 'logit_10': -3.866785583066424}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:09,240] Trial 31 finished with value: 0.45697913418899866 and parameters: {'logit_0': -2.297985482524931, 'logit_1': 0.26079183449974774, 'logit_2': -0.014956373094866193, 'logit_3': -3.0372560170381746, 'logit_4': -2.074726220252464, 'logit_5': 3.3203867391901722, 'logit_6': -3.2315919170482, 'logit_7': -3.0016790087791594, 'logit_8': 2.8227852120693138, 'logit_9': -2.6648711479383302, 'logit_10': -0.1406824007614369}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:11,313] Trial 32 finished with value: 0.4563422876421714 and parameters: {'logit_0': -3.5534558812978214, 'logit_1': 0.5436454256063397, 'logit_2': -0.22228500525740075, 'logit_3': -2.660749732043124, 'logit_4': -2.3926281673618472, 'logit_5': 3.2311784671487787, 'logit_6': -3.3334346173540133, 'logit_7': -3.091842103384323, 'logit_8': 2.1833512423829986, 'logit_9': -1.72550043606264, 'logit_10': 0.1804787414945176}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:13,407] Trial 33 finished with value: 0.45359692944418295 and parameters: {'logit_0': -3.886934508281958, 'logit_1': 0.44667624725405797, 'logit_2': -0.3890718084121431, 'logit_3': -2.8179393880661774, 'logit_4': -2.4537681018897635, 'logit_5': 3.583751031318649, 'logit_6': -3.4075555454577753, 'logit_7': -3.4316868565409075, 'logit_8': 3.420244963850892, 'logit_9': -1.6355189875800362, 'logit_10': 0.3093539592719423}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:15,463] Trial 34 finished with value: 0.4424014919847721 and parameters: {'logit_0': -2.493877460687425, 'logit_1': -0.9861774282465423, 'logit_2': 0.7111202979237732, 'logit_3': -2.5166766200505317, 'logit_4': -2.8901038136972366, 'logit_5': 3.9912726641502894, 'logit_6': -3.958074382902452, 'logit_7': -2.9438721332524995, 'logit_8': -2.579232772893727, 'logit_9': -0.9285969985559608, 'logit_10': 0.06263899422022551}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:17,542] Trial 35 finished with value: 0.3875468203291934 and parameters: {'logit_0': -1.6217920126046526, 'logit_1': 0.7280690209981933, 'logit_2': 1.4380896591855636, 'logit_3': -3.9426071037659773, 'logit_4': -2.1338118252586313, 'logit_5': -0.441979184779113, 'logit_6': -3.233193823936056, 'logit_7': -3.038484329995608, 'logit_8': -0.5788453470601247, 'logit_9': -2.416749764319405, 'logit_10': 2.402589910690337}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:19,742] Trial 36 finished with value: 0.44511038293310967 and parameters: {'logit_0': -3.555565235244022, 'logit_1': 0.2143369380727378, 'logit_2': -2.147770674068306, 'logit_3': -1.260753348738473, 'logit_4': -0.1754823141397588, 'logit_5': 2.4253327833552136, 'logit_6': -2.3901083753926153, 'logit_7': -3.937953653908909, 'logit_8': 0.6183168096274798, 'logit_9': 0.49958318923198675, 'logit_10': 0.8854818939071813}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:21,871] Trial 37 finished with value: 0.4287179965099961 and parameters: {'logit_0': -3.0690094219615647, 'logit_1': -0.8271173736037318, 'logit_2': -0.13072559037884007, 'logit_3': -2.5119451776549004, 'logit_4': -1.276184292841787, 'logit_5': 1.5461791347299347, 'logit_6': -2.218827017960259, 'logit_7': -3.248026964038231, 'logit_8': 2.8781472127304095, 'logit_9': -2.164197946718441, 'logit_10': 1.469436597542216}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:23,985] Trial 38 finished with value: 0.4492816975900469 and parameters: {'logit_0': -2.024203164704839, 'logit_1': 1.58862015392206, 'logit_2': -0.8798640567975733, 'logit_3': -3.5811132080099766, 'logit_4': 0.543133598965643, 'logit_5': 1.8900048343187432, 'logit_6': -3.1546949190813107, 'logit_7': -2.6673472606565687, 'logit_8': 2.169893849239568, 'logit_9': -1.8529667197127648, 'logit_10': -0.9091451957173837}. Best is trial 9 with value: 0.4590129422501954.
[I 2026-07-30 09:36:26,122] Trial 39 finished with value: 0.4217205112578215 and parameters: {'logit_0': -3.5686797369092043, 'logit_1': -1.6655430529631485, 'logit_2': -2.0702277355577734, 'logit_3': -3.2910213621095306, 'logit_4': -2.2279489550766067, 'logit_5': 0.7774727540384307, 'logit_6': -3.9325973854801344, 'logit_7': 1.9460054088384102, 'logit_8': 3.6683019099164604, 'logit_9': 1.1376719378090456, 'logit_10': -3.4453562290184836}. Best is trial 9 with value: 0.4590129422501954.

[I 2026-07-30 09:40:21,544] A new study created in memory with name: no-name-5b4ce2bb-f96a-4b38-b68b-88e5962a3134

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-07-30 09:40:24,040] Trial 0 finished with value: 0.4012183766236799 and parameters: {'logit_0': -1.0036790492211, 'logit_1': 3.6057144512793293, 'logit_2': 1.8559515344912407, 'logit_3': 0.7892678735762928, 'logit_4': -2.751850876460508, 'logit_5': -2.752043837310379, 'logit_6': -3.5353311026544043, 'logit_7': 2.9294091661994814, 'logit_8': 0.8089200939456704, 'logit_9': 1.664580622368364, 'logit_10': -3.8353240456335804}. Best is trial 0 with value: 0.4012183766236799.
[I 2026-07-30 09:40:26,536] Trial 1 finished with value: 0.4019335095332853 and parameters: {'logit_0': 3.7592788172959546, 'logit_1': 2.659541126403374, 'logit_2': -2.3012871145737908, 'logit_3': -2.545400262343195, 'logit_4': -2.5327639211725295, 'logit_5': -1.5660620563236982, 'logit_6': 0.19805145305790273, 'logit_7': -0.5444398508630739, 'logit_8': -1.6701668784156647, 'logit_9': 0.8948231577790358, 'logit_10': -2.8840491147836653}. Best is trial 1 with value: 0.4019335095332853.
[I 2026-07-30 09:40:29,142] Trial 2 finished with value: 0.4088427986013297 and parameters: {'logit_0': -1.6628428117182548, 'logit_1': -1.0691052536504664, 'logit_2': -0.35144012626371257, 'logit_3': 2.281407691144109, 'logit_4': -2.402609742733122, 'logit_5': 0.11387550730889284, 'logit_6': 0.7393165508963397, 'logit_7': -3.628396698240018, 'logit_8': 0.8603588152115069, 'logit_9': -2.6358070105016678, 'logit_10': -3.479587256117764}. Best is trial 2 with value: 0.4088427986013297.
[I 2026-07-30 09:40:31,668] Trial 3 finished with value: 0.3932616576352686 and parameters: {'logit_0': 3.591084298026666, 'logit_1': 3.725056264596475, 'logit_2': 2.467178784931689, 'logit_3': -1.5630898466130345, 'logit_4': -3.218623087948929, 'logit_5': 1.4738642120972552, 'logit_6': -0.4787800500831896, 'logit_7': -3.0236941212417694, 'logit_8': -0.03858471910983852, 'logit_9': -3.724891831078253, 'logit_10': 3.2745632166302565}. Best is trial 2 with value: 0.4088427986013297.
[I 2026-07-30 09:40:34,203] Trial 4 finished with value: 0.4196024822391398 and parameters: {'logit_0': -1.9297601471998647, 'logit_1': 1.3001782748318558, 'logit_2': -1.5063113912847124, 'logit_3': 0.1605441694224865, 'logit_4': 0.3736822347462372, 'logit_5': -2.5211643557957837, 'logit_6': 3.7566770221164685, 'logit_7': 2.2010625868889164, 'logit_8': 3.515991532513513, 'logit_9': 3.1586188034211906, 'logit_10': 0.7831998304886811}. Best is trial 4 with value: 0.4196024822391398.
[I 2026-07-30 09:40:36,653] Trial 5 finished with value: 0.3792903362977353 and parameters: {'logit_0': 3.3749938801849346, 'logit_1': -3.292059983584644, 'logit_2': -2.4321371006468384, 'logit_3': -3.6381816887156955, 'logit_4': -1.3973573538938853, 'logit_5': -0.8905816824841439, 'logit_6': -1.8292077458088327, 'logit_7': 2.6299000732154347, 'logit_8': -1.1459733864512858, 'logit_9': -1.752523922500954, 'logit_10': 0.3415686652659877}. Best is trial 4 with value: 0.4196024822391398.
[I 2026-07-30 09:40:39,103] Trial 6 finished with value: 0.3966071510939727 and parameters: {'logit_0': -2.872606200201899, 'logit_1': 2.4175758460323173, 'logit_2': -3.4035948505618334, 'logit_3': 3.8950954928041384, 'logit_4': 2.1779581543732593, 'logit_5': -2.4102745477266208, 'logit_6': -3.955823063011181, 'logit_7': 2.5236914276386733, 'logit_8': 1.654858750780937, 'logit_9': 1.8320573443278985, 'logit_10': 2.170162773487566}. Best is trial 4 with value: 0.4196024822391398.
[I 2026-07-30 09:40:41,611] Trial 7 finished with value: 0.4086719989938705 and parameters: {'logit_0': -3.407642786127277, 'logit_1': -1.1322741716458191, 'logit_2': -3.0730475237989623, 'logit_3': 2.904827407004748, 'logit_4': 0.9863850146204634, 'logit_5': -1.3528158011788065, 'logit_6': -3.491533197711811, 'logit_7': -1.5121414262747024, 'logit_8': -1.3985334237860236, 'logit_9': 1.8368494267045126, 'logit_10': 1.100459770841705}. Best is trial 4 with value: 0.4196024822391398.
[I 2026-07-30 09:40:44,049] Trial 8 finished with value: 0.4031033546519957 and parameters: {'logit_0': 3.0977019406106123, 'logit_1': -0.22228059870440564, 'logit_2': -3.0432460324935864, 'logit_3': 1.70595829778396, 'logit_4': 2.0862803889351795, 'logit_5': 0.49021758055596987, 'logit_6': 2.167737439636488, 'logit_7': -0.049635229084874055, 'logit_8': 0.18186263505595246, 'logit_9': -0.579671853131603, 'logit_10': -3.7966469860472385}. Best is trial 4 with value: 0.4196024822391398.
[I 2026-07-30 09:40:46,533] Trial 9 finished with value: 0.43485974081478357 and parameters: {'logit_0': -3.1368685840535644, 'logit_1': -3.748566514506126, 'logit_2': 1.0912832901102432, 'logit_3': -1.4851521513893866, 'logit_4': 0.06856552931762216, 'logit_5': 3.260531791408744, 'logit_6': -2.0056621668090004, 'logit_7': -0.7169366157149621, 'logit_8': 2.0444091083443894, 'logit_9': -2.1696146760670203, 'logit_10': -3.384160721369656}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:40:49,045] Trial 10 finished with value: 0.41161130733992723 and parameters: {'logit_0': 1.5983752813836336, 'logit_1': -3.9520225363534633, 'logit_2': 3.7562968863029287, 'logit_3': -1.2251928687470248, 'logit_4': 3.585942154213804, 'logit_5': 3.261318362260143, 'logit_6': -1.9365843791880635, 'logit_7': 1.1037740416884878, 'logit_8': -3.2242497620137636, 'logit_9': -0.9229993470990747, 'logit_10': -1.7539123660823663}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:40:51,535] Trial 11 finished with value: 0.43419347398572283 and parameters: {'logit_0': -2.0150121797195597, 'logit_1': 1.0170185513457526, 'logit_2': -0.42563927983813565, 'logit_3': -0.21828794673641028, 'logit_4': -0.4908264341612085, 'logit_5': -3.903679969407241, 'logit_6': 3.3141061598367223, 'logit_7': 1.2669635101900585, 'logit_8': 3.7402607119226046, 'logit_9': 3.760007008873687, 'logit_10': -1.2344500380138657}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:40:54,013] Trial 12 finished with value: 0.4294192656812713 and parameters: {'logit_0': 0.40308389787937404, 'logit_1': -2.749759547885435, 'logit_2': 0.5669919017831591, 'logit_3': -0.826069422121601, 'logit_4': -0.7973245803453533, 'logit_5': -3.8535019591560795, 'logit_6': 3.862579281086025, 'logit_7': -1.5421583731306967, 'logit_8': 3.994899509132413, 'logit_9': 3.7877586651539947, 'logit_10': -1.2591120395830275}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:40:56,502] Trial 13 finished with value: 0.43222859606404385 and parameters: {'logit_0': -3.784012978800206, 'logit_1': 1.1117789912097658, 'logit_2': 0.3206356716495351, 'logit_3': -2.5403436212004564, 'logit_4': -0.6767112325061475, 'logit_5': 3.500203774043184, 'logit_6': 1.9047867370098617, 'logit_7': 1.048674748311723, 'logit_8': 2.6930462853920196, 'logit_9': -3.6388151722018307, 'logit_10': -1.646067196456805}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:40:59,027] Trial 14 finished with value: 0.38927725515782424 and parameters: {'logit_0': -0.3128742871194379, 'logit_1': -1.78188803745514, 'logit_2': 1.380480082186068, 'logit_3': -0.12800422408054105, 'logit_4': 1.0504097089582167, 'logit_5': 2.0956877161811063, 'logit_6': -1.4361903171668424, 'logit_7': 3.835404734181955, 'logit_8': 2.372015247379016, 'logit_9': 0.34922161536110297, 'logit_10': -0.5873578488829336}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:41:01,563] Trial 15 finished with value: 0.3848190027283171 and parameters: {'logit_0': -2.5117170102156754, 'logit_1': 0.4850865473645323, 'logit_2': -0.6045376319459694, 'logit_3': 1.0346293282385242, 'logit_4': -1.4969457774897426, 'logit_5': -3.992954681282216, 'logit_6': 2.139335568797807, 'logit_7': 0.9635029458263396, 'logit_8': 2.8964173199812078, 'logit_9': -1.869687989116131, 'logit_10': -2.2870867097016294}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:41:04,011] Trial 16 finished with value: 0.43321406245497757 and parameters: {'logit_0': -1.2124627174761087, 'logit_1': -1.9714466506748507, 'logit_2': -0.9952406362234034, 'logit_3': -2.217190031276859, 'logit_4': 0.33439194065234645, 'logit_5': 2.298302085733763, 'logit_6': -0.8799015125849905, 'logit_7': -1.3404073125318572, 'logit_8': 1.565941098647301, 'logit_9': -2.7262828705863393, 'logit_10': -0.6641023414766348}. Best is trial 9 with value: 0.43485974081478357.
[I 2026-07-30 09:41:06,465] Trial 17 finished with value: 0.43588982446247165 and parameters: {'logit_0': -2.636309771743096, 'logit_1': 0.017833619982771554, 'logit_2': 3.29664914394153, 'logit_3': -0.48319025283985706, 'logit_4': -3.8666910573496756, 'logit_5': 0.9820462670136019, 'logit_6': -2.6293346194475395, 'logit_7': -2.2538716936207743, 'logit_8': 3.357952938632566, 'logit_9': 3.2888410752654798, 'logit_10': -2.3665361091168364}. Best is trial 17 with value: 0.43588982446247165.
[I 2026-07-30 09:41:09,007] Trial 18 finished with value: 0.4261785415370952 and parameters: {'logit_0': 0.6108581201120318, 'logit_1': -0.30770757108801816, 'logit_2': 3.6380763975245305, 'logit_3': -3.959211695055833, 'logit_4': -3.715179310763926, 'logit_5': 1.0844063439139595, 'logit_6': -2.5263251750124596, 'logit_7': -2.599496331568082, 'logit_8': 1.8751285327145641, 'logit_9': 2.9347258726115637, 'logit_10': -2.761029714807556}. Best is trial 17 with value: 0.43588982446247165.
[I 2026-07-30 09:41:11,515] Trial 19 finished with value: 0.43168606657063685 and parameters: {'logit_0': -3.9947980454343854, 'logit_1': -2.693271673040053, 'logit_2': 2.7492470033500154, 'logit_3': -1.9417577853977288, 'logit_4': -3.9954912927147754, 'logit_5': 2.7921306750906987, 'logit_6': -2.7329457517707714, 'logit_7': -2.6625282885137485, 'logit_8': 3.029016052664266, 'logit_9': -0.7539707160118487, 'logit_10': -2.6088091292878746}. Best is trial 17 with value: 0.43588982446247165.
[I 2026-07-30 09:41:14,016] Trial 20 finished with value: 0.4190744087306999 and parameters: {'logit_0': -3.042285052644827, 'logit_1': 2.114154429545187, 'logit_2': 1.0379854927874592, 'logit_3': -0.683134481990503, 'logit_4': -1.654794720251871, 'logit_5': 3.9797586278477866, 'logit_6': -2.888380449604875, 'logit_7': -0.6379145843367251, 'logit_8': 2.1949529507797414, 'logit_9': 0.7490962162035326, 'logit_10': 3.9943478166701825}. Best is trial 17 with value: 0.43588982446247165.
[I 2026-07-30 09:41:16,783] Trial 21 finished with value: 0.44037320003614944 and parameters: {'logit_0': -2.199815578270998, 'logit_1': 0.7655430986812739, 'logit_2': 2.89743267820173, 'logit_3': -0.007924954829196466, 'logit_4': -0.5173280564960548, 'logit_5': -0.30205765910992777, 'logit_6': 0.8362638325707623, 'logit_7': 0.3559338517986631, 'logit_8': 3.9600935635802803, 'logit_9': 3.910532123871547, 'logit_10': -0.8513538912287222}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:19,313] Trial 22 finished with value: 0.4261490973560749 and parameters: {'logit_0': -2.6243183404291512, 'logit_1': 0.31182991985109343, 'logit_2': 2.664642347569247, 'logit_3': 0.7606275772925781, 'logit_4': 1.647261323768769, 'logit_5': -0.2816518085472849, 'logit_6': 0.5619953611207749, 'logit_7': 0.17859027657979834, 'logit_8': 3.4392875226278363, 'logit_9': 2.410793407561123, 'logit_10': -0.39291822572741064}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:21,863] Trial 23 finished with value: 0.42341741094788304 and parameters: {'logit_0': -0.7754722220034398, 'logit_1': -0.443943017261033, 'logit_2': 3.2032795366708826, 'logit_3': -1.035916556408112, 'logit_4': 3.419116185795156, 'logit_5': 1.1558465331474097, 'logit_6': 1.1546116056219704, 'logit_7': -2.1773215422346874, 'logit_8': 3.1164939227352226, 'logit_9': 2.603388829569356, 'logit_10': -2.148592332080111}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:24,337] Trial 24 finished with value: 0.43702446818962803 and parameters: {'logit_0': -2.2139220906105677, 'logit_1': -1.4125244734173026, 'logit_2': 1.8983870144071764, 'logit_3': -2.9845311798153418, 'logit_4': 2.766156493101325, 'logit_5': -0.4689748162791485, 'logit_6': -0.5695326232836062, 'logit_7': -0.7392516604175517, 'logit_8': 3.8816619805621873, 'logit_9': 3.870825963092379, 'logit_10': -3.022947886871595}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:26,808] Trial 25 finished with value: 0.43858064102031674 and parameters: {'logit_0': -2.36198710761222, 'logit_1': -1.0106078965375176, 'logit_2': 2.08954434701874, 'logit_3': -3.1883942317348795, 'logit_4': 2.527852739600922, 'logit_5': -0.4441320837843854, 'logit_6': -0.9094014663729667, 'logit_7': -3.891371905074795, 'logit_8': 3.8469089669909016, 'logit_9': 3.9128594207304483, 'logit_10': -3.105318177060534}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:29,287] Trial 26 finished with value: 0.4281006488154181 and parameters: {'logit_0': 1.3974295525030676, 'logit_1': -1.1640577932524834, 'logit_2': 2.0398727350006327, 'logit_3': -3.170178187636563, 'logit_4': 2.9723484428396953, 'logit_5': -0.5800543561075373, 'logit_6': -0.3667169277072375, 'logit_7': -3.8375088198031126, 'logit_8': -3.5653219507423657, 'logit_9': 3.9715428050570383, 'logit_10': 1.830186851566736}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:31,765] Trial 27 finished with value: 0.4202244299984976 and parameters: {'logit_0': -1.5017129537107237, 'logit_1': -1.911645136843033, 'logit_2': 1.7151122235412197, 'logit_3': -2.977417191157797, 'logit_4': 2.882813821120539, 'logit_5': -1.5074566776621094, 'logit_6': -1.1569022861098683, 'logit_7': 0.42137422081902365, 'logit_8': 3.987973500395368, 'logit_9': 2.288723403400672, 'logit_10': -3.153415891976942}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:34,498] Trial 28 finished with value: 0.43679134025651406 and parameters: {'logit_0': -2.2561312332497985, 'logit_1': -0.7930740438642969, 'logit_2': 2.390993680790009, 'logit_3': -3.1395752003327204, 'logit_4': 2.4894509029857845, 'logit_5': 0.32535572521427025, 'logit_6': 1.3918135547687993, 'logit_7': 1.7073109733526484, 'logit_8': 2.620264933229259, 'logit_9': 3.39524682288239, 'logit_10': -1.0596207225169971}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:37,305] Trial 29 finished with value: 0.384779548831097 and parameters: {'logit_0': -0.7476029954926178, 'logit_1': 1.6203166603669503, 'logit_2': 1.849149739826521, 'logit_3': -3.5246440735598408, 'logit_4': 1.3040847333090073, 'logit_5': -2.0518835641698256, 'logit_6': -0.09143918453037345, 'logit_7': 3.4689307864848997, 'logit_8': 0.8230156987983537, 'logit_9': 1.468932315531366, 'logit_10': 0.07594410956031536}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:39,990] Trial 30 finished with value: 0.414116887609775 and parameters: {'logit_0': -0.20028595213777695, 'logit_1': 3.1039226344247837, 'logit_2': 3.088039997749297, 'logit_3': 0.4851988858492609, 'logit_4': 3.674858094753701, 'logit_5': -3.18706327898317, 'logit_6': -0.8671640783265862, 'logit_7': -3.224836191603084, 'logit_8': 1.2984876996040238, 'logit_9': 2.783601369709171, 'logit_10': -3.890512673496616}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:42,753] Trial 31 finished with value: 0.43904777000971296 and parameters: {'logit_0': -2.2477674625909745, 'logit_1': -0.6140578472946054, 'logit_2': 2.246607342032474, 'logit_3': -3.0108365367296095, 'logit_4': 2.597920793514769, 'logit_5': 0.030117619789917338, 'logit_6': 1.525157294748976, 'logit_7': 2.0286274588476236, 'logit_8': 2.6412507540423924, 'logit_9': 3.668462632142191, 'logit_10': -1.144643762791922}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:45,396] Trial 32 finished with value: 0.4310359787728889 and parameters: {'logit_0': -1.1536535240475685, 'logit_1': 0.5436454256063397, 'logit_2': 2.116896778528449, 'logit_3': -2.10945037792228, 'logit_4': 2.9394292139625815, 'logit_5': -0.6420023897049839, 'logit_6': 2.8179468677300825, 'logit_7': 1.896850588401512, 'logit_8': 3.496753270569308, 'logit_9': 3.58203565489921, 'logit_10': -1.7857831837673612}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:47,952] Trial 33 finished with value: 0.4328224117550751 and parameters: {'logit_0': -1.7042851204520504, 'logit_1': -1.5725691274258138, 'logit_2': 3.9164588252880037, 'logit_3': -2.8989912971021097, 'logit_4': 1.7681869715588943, 'logit_5': -0.14836399873910078, 'logit_6': 0.38596828824553964, 'logit_7': 2.9952644746533164, 'logit_8': 2.9307249585418176, 'logit_9': 3.8955668355551536, 'logit_10': -2.9011714944992812}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:50,575] Trial 34 finished with value: 0.41651645308410645 and parameters: {'logit_0': -3.3991182936082454, 'logit_1': -2.380544957768008, 'logit_2': 1.5006084008072715, 'logit_3': -2.421180063179027, 'logit_4': 3.8973406162412036, 'logit_5': -1.119966860419366, 'logit_6': 1.0364860483861156, 'logit_7': 0.4101288760328683, 'logit_8': 3.979568096179894, 'logit_9': 1.2714693804652937, 'logit_10': -1.9998472732257946}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:53,273] Trial 35 finished with value: 0.4403351001906486 and parameters: {'logit_0': -1.9031108452715682, 'logit_1': -0.7172057607683219, 'logit_2': 0.8110973866009139, 'logit_3': -3.949101022913445, 'logit_4': 0.735596932189654, 'logit_5': 0.6618729552899332, 'logit_6': 0.057777513513249446, 'logit_7': -0.25866140731406206, 'logit_8': -0.5788453470601247, 'logit_9': 3.174732873488551, 'logit_10': -3.320072690675962}. Best is trial 21 with value: 0.44037320003614944.
[I 2026-07-30 09:41:55,859] Trial 36 finished with value: 0.4428863393967309 and parameters: {'logit_0': -1.3260063260543364, 'logit_1': -0.6930767779289533, 'logit_2': 0.7231238978842667, 'logit_3': -3.5141640661306233, 'logit_4': 0.467796798350556, 'logit_5': 0.5998275299335003, 'logit_6': 0.08783147810288228, 'logit_7': -0.13945934785612435, 'logit_8': -0.5330912237169457, 'logit_9': 3.043487969686914, 'logit_10': 0.5701925188743486}. Best is trial 36 with value: 0.4428863393967309.
[I 2026-07-30 09:41:58,804] Trial 37 finished with value: 0.4346533811778882 and parameters: {'logit_0': -1.5120241553536184, 'logit_1': -0.6918891832874849, 'logit_2': 0.05975267388890626, 'logit_3': -3.90900107735705, 'logit_4': 0.7834468088952966, 'logit_5': 0.5781042054459401, 'logit_6': 0.06204468939203167, 'logit_7': -0.05568025134612603, 'logit_8': -0.44363816727541844, 'logit_9': 2.2024083590633263, 'logit_10': 1.0530907669974021}. Best is trial 36 with value: 0.4428863393967309.
[I 2026-07-30 09:42:02,077] Trial 38 finished with value: 0.4474128065101692 and parameters: {'logit_0': -0.7072469410572682, 'logit_1': 0.05367697296832674, 'logit_2': 0.8076678211909407, 'logit_3': -3.638170678005652, 'logit_4': -0.2415584929991222, 'logit_5': 1.6928329712340813, 'logit_6': 1.6349403755925942, 'logit_7': 0.5777207019804231, 'logit_8': -2.298552856883383, 'logit_9': 3.0735950265492287, 'logit_10': 0.49185091663296454}. Best is trial 38 with value: 0.4474128065101692.
[I 2026-07-30 09:42:04,858] Trial 39 finished with value: 0.4287381507025099 and parameters: {'logit_0': 0.49342990507064954, 'logit_1': 1.575876959044073, 'logit_2': 0.6775685773915194, 'logit_3': -3.608814805063508, 'logit_4': -0.26828208629739486, 'logit_5': 1.7361332682552295, 'logit_6': 0.701059463258794, 'logit_7': 0.6709760673026518, 'logit_8': -2.447249465526, 'logit_9': 3.0760603714683654, 'logit_10': 2.1139286443882943}. Best is trial 38 with value: 0.4474128065101692.

,pr_auc,ndcg_at_50,precision_at_50,lift_at_50,fold,train_end,valid_start,valid_end,inner_best_objective
0,0.304624,0.769912,0.423704,2.512606,1,2023-05-19,2023-06-16,2023-10-16,0.442637
1,0.329374,0.789278,0.432533,2.483961,2,2024-02-14,2024-03-13,2024-07-15,0.431390
2,0.334475,0.756798,0.424267,2.266012,3,2024-11-07,2024-12-05,2025-04-08,0.467502
3,0.457166,0.818982,0.545476,1.761783,4,2025-08-04,2025-09-01,2025-12-30,0.451565

Outer PR-AUC instability: 0.05925730599937547

## 7. Kunci bobot, lalu buka final test 2026 sekali

Bobot final dioptimalkan hanya pada development set pra-2026. Setelah sel ini berjalan, jangan kembali mengubah target, fitur, split, atau hyperparameter berdasarkan hasil 2026.

In [8]:
final_inner = make_walk_forward_folds(development['date'], n_folds=5, min_train_months=18, valid_months=3)
final_study, final_weights = optimize_weights(development, final_inner, n_trials=N_TRIALS)
final_directions = learn_directions(development)

locked_model = pd.DataFrame({
    'feature': FEATURES,
    'rank_feature': RANK_FEATURES,
    'weight': final_weights,
    'direction': final_directions
}).sort_values('weight', ascending=False)
locked_model.to_csv(OUTPUT_DIR / 'locked_weights_pre2026.csv', index=False)
with open(OUTPUT_DIR / 'locked_model_metadata.json', 'w') as f:
    json.dump({'optimized_through': str(development.date.max().date()),
               'final_test_start': str(FINAL_TEST_START.date()),
               'best_inner_objective': final_study.best_value,
               'target_abnormal_return': TARGET_ABNORMAL_RETURN,
               'target_max_volume_ratio': TARGET_MAX_VOLUME_RATIO,
               'horizon': HORIZON, 'seed': SEED}, f, indent=2)
display(locked_model)

final_test = model_data[model_data['date'] >= FINAL_TEST_START].copy()
if final_test.empty:
    print('Belum ada baris 2026 dengan label horizon lengkap.')
else:
    final_scored = score_frame(final_test, final_weights, final_directions)
    final_metrics = pd.Series(evaluate(final_scored), name='2026 untouched test')
    display(final_metrics.to_frame())
    final_scored.to_parquet(OUTPUT_DIR / 'final_test_2026_scored.parquet', index=False)

[I 2026-07-30 09:47:10,409] A new study created in memory with name: no-name-c1cf2231-4fdb-4fb9-8f15-3bd75b1a0a6b

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-07-30 09:47:15,336] Trial 0 finished with value: 0.40613144744285684 and parameters: {'logit_0': -1.0036790492211, 'logit_1': 3.6057144512793293, 'logit_2': 1.8559515344912407, 'logit_3': 0.7892678735762928, 'logit_4': -2.751850876460508, 'logit_5': -2.752043837310379, 'logit_6': -3.5353311026544043, 'logit_7': 2.9294091661994814, 'logit_8': 0.8089200939456704, 'logit_9': 1.664580622368364, 'logit_10': -3.8353240456335804}. Best is trial 0 with value: 0.40613144744285684.
[I 2026-07-30 09:47:20,417] Trial 1 finished with value: 0.4137451477966839 and parameters: {'logit_0': 3.7592788172959546, 'logit_1': 2.659541126403374, 'logit_2': -2.3012871145737908, 'logit_3': -2.545400262343195, 'logit_4': -2.5327639211725295, 'logit_5': -1.5660620563236982, 'logit_6': 0.19805145305790273, 'logit_7': -0.5444398508630739, 'logit_8': -1.6701668784156647, 'logit_9': 0.8948231577790358, 'logit_10': -2.8840491147836653}. Best is trial 1 with value: 0.4137451477966839.
[I 2026-07-30 09:47:27,934] Trial 2 finished with value: 0.4190886753790428 and parameters: {'logit_0': -1.6628428117182548, 'logit_1': -1.0691052536504664, 'logit_2': -0.35144012626371257, 'logit_3': 2.281407691144109, 'logit_4': -2.402609742733122, 'logit_5': 0.11387550730889284, 'logit_6': 0.7393165508963397, 'logit_7': -3.628396698240018, 'logit_8': 0.8603588152115069, 'logit_9': -2.6358070105016678, 'logit_10': -3.479587256117764}. Best is trial 2 with value: 0.4190886753790428.
[I 2026-07-30 09:47:39,752] Trial 3 finished with value: 0.4014590531651537 and parameters: {'logit_0': 3.591084298026666, 'logit_1': 3.725056264596475, 'logit_2': 2.467178784931689, 'logit_3': -1.5630898466130345, 'logit_4': -3.218623087948929, 'logit_5': 1.4738642120972552, 'logit_6': -0.4787800500831896, 'logit_7': -3.0236941212417694, 'logit_8': -0.03858471910983852, 'logit_9': -3.724891831078253, 'logit_10': 3.2745632166302565}. Best is trial 2 with value: 0.4190886753790428.
[I 2026-07-30 09:47:45,378] Trial 4 finished with value: 0.4449808085875888 and parameters: {'logit_0': -1.9297601471998647, 'logit_1': 1.3001782748318558, 'logit_2': -1.5063113912847124, 'logit_3': 0.1605441694224865, 'logit_4': 0.3736822347462372, 'logit_5': -2.5211643557957837, 'logit_6': 3.7566770221164685, 'logit_7': 2.2010625868889164, 'logit_8': 3.515991532513513, 'logit_9': 3.1586188034211906, 'logit_10': 0.7831998304886811}. Best is trial 4 with value: 0.4449808085875888.
[I 2026-07-30 09:47:51,049] Trial 5 finished with value: 0.39581177764742514 and parameters: {'logit_0': 3.3749938801849346, 'logit_1': -3.292059983584644, 'logit_2': -2.4321371006468384, 'logit_3': -3.6381816887156955, 'logit_4': -1.3973573538938853, 'logit_5': -0.8905816824841439, 'logit_6': -1.8292077458088327, 'logit_7': 2.6299000732154347, 'logit_8': -1.1459733864512858, 'logit_9': -1.752523922500954, 'logit_10': 0.3415686652659877}. Best is trial 4 with value: 0.4449808085875888.
[I 2026-07-30 09:47:56,584] Trial 6 finished with value: 0.4110279162795882 and parameters: {'logit_0': -2.872606200201899, 'logit_1': 2.4175758460323173, 'logit_2': -3.4035948505618334, 'logit_3': 3.8950954928041384, 'logit_4': 2.1779581543732593, 'logit_5': -2.4102745477266208, 'logit_6': -3.955823063011181, 'logit_7': 2.5236914276386733, 'logit_8': 1.654858750780937, 'logit_9': 1.8320573443278985, 'logit_10': 2.170162773487566}. Best is trial 4 with value: 0.4449808085875888.
[I 2026-07-30 09:48:02,574] Trial 7 finished with value: 0.41896176747593683 and parameters: {'logit_0': -3.407642786127277, 'logit_1': -1.1322741716458191, 'logit_2': -3.0730475237989623, 'logit_3': 2.904827407004748, 'logit_4': 0.9863850146204634, 'logit_5': -1.3528158011788065, 'logit_6': -3.491533197711811, 'logit_7': -1.5121414262747024, 'logit_8': -1.3985334237860236, 'logit_9': 1.8368494267045126, 'logit_10': 1.100459770841705}. Best is trial 4 with value: 0.4449808085875888.
[I 2026-07-30 09:48:08,058] Trial 8 finished with value: 0.4156004968266849 and parameters: {'logit_0': 3.0977019406106123, 'logit_1': -0.22228059870440564, 'logit_2': -3.0432460324935864, 'logit_3': 1.70595829778396, 'logit_4': 2.0862803889351795, 'logit_5': 0.49021758055596987, 'logit_6': 2.167737439636488, 'logit_7': -0.049635229084874055, 'logit_8': 0.18186263505595246, 'logit_9': -0.579671853131603, 'logit_10': -3.7966469860472385}. Best is trial 4 with value: 0.4449808085875888.
[I 2026-07-30 09:48:13,563] Trial 9 finished with value: 0.45311600706654265 and parameters: {'logit_0': -3.1368685840535644, 'logit_1': -3.748566514506126, 'logit_2': 1.0912832901102432, 'logit_3': -1.4851521513893866, 'logit_4': 0.06856552931762216, 'logit_5': 3.260531791408744, 'logit_6': -2.0056621668090004, 'logit_7': -0.7169366157149621, 'logit_8': 2.0444091083443894, 'logit_9': -2.1696146760670203, 'logit_10': -3.384160721369656}. Best is trial 9 with value: 0.45311600706654265.
[I 2026-07-30 09:48:19,148] Trial 10 finished with value: 0.4158689573171371 and parameters: {'logit_0': 1.5983752813836336, 'logit_1': -3.9520225363534633, 'logit_2': 3.7562968863029287, 'logit_3': -1.2251928687470248, 'logit_4': 3.585942154213804, 'logit_5': 3.261318362260143, 'logit_6': -1.9365843791880635, 'logit_7': 1.1037740416884878, 'logit_8': -3.2242497620137636, 'logit_9': -0.9229993470990747, 'logit_10': -1.7539123660823663}. Best is trial 9 with value: 0.45311600706654265.
[I 2026-07-30 09:48:25,258] Trial 11 finished with value: 0.4570497966303038 and parameters: {'logit_0': -2.0150121797195597, 'logit_1': 1.0170185513457526, 'logit_2': -0.42563927983813565, 'logit_3': -0.21828794673641028, 'logit_4': -0.4908264341612085, 'logit_5': -3.903679969407241, 'logit_6': 3.3141061598367223, 'logit_7': 1.2669635101900585, 'logit_8': 3.7402607119226046, 'logit_9': 3.760007008873687, 'logit_10': -1.2344500380138657}. Best is trial 11 with value: 0.4570497966303038.
[I 2026-07-30 09:48:32,504] Trial 12 finished with value: 0.4515544752203164 and parameters: {'logit_0': 0.40308389787937404, 'logit_1': -2.749759547885435, 'logit_2': 0.5669919017831591, 'logit_3': -0.826069422121601, 'logit_4': -0.7973245803453533, 'logit_5': -3.8535019591560795, 'logit_6': 3.862579281086025, 'logit_7': -1.5421583731306967, 'logit_8': 3.994899509132413, 'logit_9': 3.7877586651539947, 'logit_10': -1.2591120395830275}. Best is trial 11 with value: 0.4570497966303038.
[I 2026-07-30 09:48:38,061] Trial 13 finished with value: 0.45391677575369477 and parameters: {'logit_0': -3.784012978800206, 'logit_1': 1.1117789912097658, 'logit_2': 0.3206356716495351, 'logit_3': -2.5403436212004564, 'logit_4': -0.6767112325061475, 'logit_5': 3.500203774043184, 'logit_6': 1.9047867370098617, 'logit_7': 1.048674748311723, 'logit_8': 2.6930462853920196, 'logit_9': -3.6388151722018307, 'logit_10': -1.646067196456805}. Best is trial 11 with value: 0.4570497966303038.
[I 2026-07-30 09:48:43,414] Trial 14 finished with value: 0.4327631196152502 and parameters: {'logit_0': -0.3813894969791326, 'logit_1': 1.0785415424111733, 'logit_2': -0.02234385313927545, 'logit_3': -3.9603829520926945, 'logit_4': -1.2745805026427932, 'logit_5': 1.968764807305416, 'logit_6': 2.1448019360709996, 'logit_7': 1.1135486971928057, 'logit_8': 2.818996975551607, 'logit_9': -3.4144177354517624, 'logit_10': -1.0646757956007913}. Best is trial 11 with value: 0.4570497966303038.
[I 2026-07-30 09:48:48,828] Trial 15 finished with value: 0.4582287952574573 and parameters: {'logit_0': -3.901541306118749, 'logit_1': 0.7395000859574469, 'logit_2': -0.6161261675445062, 'logit_3': -2.63704953441266, 'logit_4': -0.8796300113246838, 'logit_5': 3.9275341223763363, 'logit_6': 2.4025901432970054, 'logit_7': 1.220318512132172, 'logit_8': 2.6041806703067802, 'logit_9': 0.06780211724218432, 'logit_10': -2.1219300045834415}. Best is trial 15 with value: 0.4582287952574573.
[I 2026-07-30 09:48:54,342] Trial 16 finished with value: 0.4393589481126629 and parameters: {'logit_0': -2.2353546446658448, 'logit_1': 0.0599341131148515, 'logit_2': -1.055822502108852, 'logit_3': 0.7324426087148321, 'logit_4': 1.1750676887449594, 'logit_5': 1.9978172252455064, 'logit_6': 2.9938542324412367, 'logit_7': 3.7218601430335605, 'logit_8': 3.2036921055982392, 'logit_9': 3.0195363179557573, 'logit_10': -0.48627786271833795}. Best is trial 15 with value: 0.4582287952574573.
[I 2026-07-30 09:48:59,926] Trial 17 finished with value: 0.4193366842147109 and parameters: {'logit_0': 0.7321413679658073, 'logit_1': 2.3521055667675164, 'logit_2': -1.096716374218417, 'logit_3': -2.684826099120115, 'logit_4': -3.902927665936752, 'logit_5': -3.9019526576518624, 'logit_6': 1.2077468029393936, 'logit_7': 1.533572080251555, 'logit_8': 1.766668589960453, 'logit_9': 0.3566360423752893, 'logit_10': -2.3665361091168364}. Best is trial 15 with value: 0.4582287952574573.
[I 2026-07-30 09:49:05,440] Trial 18 finished with value: 0.4080901047976568 and parameters: {'logit_0': -2.643347764897986, 'logit_1': 0.17995209884775443, 'logit_2': 1.131058924974119, 'logit_3': -0.6518944035111738, 'logit_4': -2.111130993039798, 'logit_5': 0.9643064878201209, 'logit_6': 2.9648805598592247, 'logit_7': 0.40965041744945396, 'logit_8': 3.8676897906695076, 'logit_9': -1.100048803375659, 'logit_10': -0.42880989743862974}. Best is trial 15 with value: 0.4582287952574573.
[I 2026-07-30 09:49:10,892] Trial 19 finished with value: 0.3931716116868196 and parameters: {'logit_0': -3.9947980454343854, 'logit_1': -1.7493425318412954, 'logit_2': -1.697161128349753, 'logit_3': -0.08409672981012026, 'logit_4': -0.5101349121941627, 'logit_5': -0.3912527271125219, 'logit_6': 2.85753591186715, 'logit_7': 3.6870169354631974, 'logit_8': 2.365849527842239, 'logit_9': 0.8822161946252689, 'logit_10': -2.39518528073937}. Best is trial 15 with value: 0.4582287952574573.
[I 2026-07-30 09:49:16,608] Trial 20 finished with value: 0.46226174069685816 and parameters: {'logit_0': -1.0913313156089455, 'logit_1': 1.785604890183645, 'logit_2': -0.636385591035095, 'logit_3': -3.0574876762470447, 'logit_4': -1.4653183099390152, 'logit_5': 3.9797586278477866, 'logit_6': -0.5935402932641951, 'logit_7': 1.8372530804837879, 'logit_8': 1.1242410669250416, 'logit_9': 3.960541597357264, 'logit_10': 3.9943478166701825}. Best is trial 20 with value: 0.46226174069685816.
[I 2026-07-30 09:49:22,451] Trial 21 finished with value: 0.46062895640076695 and parameters: {'logit_0': -1.113027811421862, 'logit_1': 1.7769708047038864, 'logit_2': -0.6832659472405, 'logit_3': -3.324114030320706, 'logit_4': -1.626843504763436, 'logit_5': 3.835143995097611, 'logit_6': -0.6967157039824281, 'logit_7': 1.7592986625681197, 'logit_8': 1.5495438738999643, 'logit_9': 3.9620073532688327, 'logit_10': 1.72986451359809}. Best is trial 20 with value: 0.46226174069685816.
[I 2026-07-30 09:49:27,819] Trial 22 finished with value: 0.46328740910566824 and parameters: {'logit_0': -0.906852536116134, 'logit_1': 2.033014405433658, 'logit_2': -0.5371062086110666, 'logit_3': -3.2351644979463905, 'logit_4': -1.7840442686843423, 'logit_5': 2.662847480798087, 'logit_6': -0.8897236977901339, 'logit_7': 1.8603909731860266, 'logit_8': 1.3330745501208634, 'logit_9': 2.4354265200567173, 'logit_10': 3.742065168887647}. Best is trial 22 with value: 0.46328740910566824.
[I 2026-07-30 09:49:33,141] Trial 23 finished with value: 0.4636227016433492 and parameters: {'logit_0': -0.895932421249694, 'logit_1': 1.717976666820228, 'logit_2': -3.9979031015622963, 'logit_3': -3.2751801553361495, 'logit_4': -2.0279087731070407, 'logit_5': 2.70351149312253, 'logit_6': -0.832364821977323, 'logit_7': 1.9857194273972374, 'logit_8': 1.0688459240055244, 'logit_9': 2.861313221849403, 'logit_10': 3.974058315564112}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:49:38,651] Trial 24 finished with value: 0.4508989787814151 and parameters: {'logit_0': -0.35711855807029624, 'logit_1': 3.1076188924044614, 'logit_2': -3.9065085933945243, 'logit_3': -2.052281812551956, 'logit_4': -1.7605061114216056, 'logit_5': 2.6468627216081346, 'logit_6': -1.1352089858090153, 'logit_7': 3.288896377648874, 'logit_8': -0.15152246494492827, 'logit_9': 2.6525211660535692, 'logit_10': 3.9622270777932287}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:49:44,033] Trial 25 finished with value: 0.4611650295483766 and parameters: {'logit_0': 0.9927133610570607, 'logit_1': 1.870876260818699, 'logit_2': -2.1855117352347717, 'logit_3': -3.149895278224787, 'logit_4': -3.284941458206867, 'logit_5': 2.5782474632137236, 'logit_6': -1.2882887540764685, 'logit_7': 2.0408744376001646, 'logit_8': 0.9284906337157126, 'logit_9': 2.5700690217593056, 'logit_10': 3.077596407872992}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:49:49,419] Trial 26 finished with value: 0.4300389317826418 and parameters: {'logit_0': -0.9779398729641557, 'logit_1': 1.771069790535738, 'logit_2': 3.0271719408703133, 'logit_3': -3.9553054095299367, 'logit_4': -3.931241043295513, 'logit_5': 2.7195095047348428, 'logit_6': 0.1345158809266036, 'logit_7': 0.4247023935146135, 'logit_8': -0.650729553162678, 'logit_9': 2.2312519208112724, 'logit_10': 3.7004296860680737}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:49:54,801] Trial 27 finished with value: 0.4458277276792909 and parameters: {'logit_0': 0.09092375477912729, 'logit_1': 3.1894763138018334, 'logit_2': 1.1366675025746655, 'logit_3': -2.143575668281926, 'logit_4': -2.0079454232252547, 'logit_5': 1.6978435210769518, 'logit_6': -2.6205622781486326, 'logit_7': 3.079678804408651, 'logit_8': 1.1937258186033008, 'logit_9': 3.3761662613315644, 'logit_10': 2.4879583764287823}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:00,598] Trial 28 finished with value: 0.42526192221429143 and parameters: {'logit_0': 1.7156126008701524, 'logit_1': 2.892519301216595, 'logit_2': -1.6165682334990303, 'logit_3': -3.1889362014059848, 'logit_4': -2.9601118677292475, 'logit_5': 0.9946239431505921, 'logit_6': 0.7161732922910842, 'logit_7': 0.5028417865877772, 'logit_8': 0.4444280709213698, 'logit_9': 1.146142943513107, 'logit_10': 2.729503538584651}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:06,195] Trial 29 finished with value: 0.45101440892824646 and parameters: {'logit_0': -1.081592052850068, 'logit_1': 0.4906159286933356, 'logit_2': 2.077552833913688, 'logit_3': -2.021363475800181, 'logit_4': -2.3261274727650836, 'logit_5': 2.937355170146019, 'logit_6': -2.692387954896647, 'logit_7': 2.795270392649133, 'logit_8': -3.8248678814389345, 'logit_9': 1.49929352914599, 'logit_10': 3.458957015836281}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:11,707] Trial 30 finished with value: 0.42744374174583993 and parameters: {'logit_0': -0.6686293785429186, 'logit_1': 3.9356517229059857, 'logit_2': -2.7307782409057815, 'logit_3': -3.1568572057186715, 'logit_4': 0.5049915512127494, 'logit_5': 2.3017135747389443, 'logit_6': -0.38968327902487804, 'logit_7': 2.0597207009981098, 'logit_8': 0.532805017225267, 'logit_9': 2.3261601696743797, 'logit_10': 1.6898520143287397}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:17,058] Trial 31 finished with value: 0.4614860219989153 and parameters: {'logit_0': 1.0335786496560448, 'logit_1': 1.9509136719873974, 'logit_2': -3.8497149687591965, 'logit_3': -3.2056110749580906, 'logit_4': -3.286878362054689, 'logit_5': 2.428936930273574, 'logit_6': -1.2585167359582772, 'logit_7': 2.302601463900661, 'logit_8': 1.0550514570897398, 'logit_9': 2.7287373465870113, 'logit_10': 3.129804944646731}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:22,426] Trial 32 finished with value: 0.4591514299730306 and parameters: {'logit_0': 2.399398853098696, 'logit_1': 1.9080878588484227, 'logit_2': -3.990639919990428, 'logit_3': -2.8105938546679274, 'logit_4': -2.9858196325296573, 'logit_5': 3.4349814761216804, 'logit_6': -1.1525315829959022, 'logit_7': 3.1129765073358806, 'logit_8': 1.2479673791373789, 'logit_9': 3.235118037471304, 'logit_10': 3.946833570154075}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:27,728] Trial 33 finished with value: 0.4571452812129167 and parameters: {'logit_0': -1.5187162916724972, 'logit_1': 2.241905890879868, 'logit_2': -3.637735428099551, 'logit_3': -3.522826944670149, 'logit_4': -2.6088360963493953, 'logit_5': 3.976273201139744, 'logit_6': -0.10237625146630303, 'logit_7': 2.300352154916641, 'logit_8': -0.59245166027841, 'logit_9': 2.832648797385139, 'logit_10': 2.9729860514984328}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:33,063] Trial 34 finished with value: 0.42988913871575213 and parameters: {'logit_0': 0.1574951353363312, 'logit_1': 3.4210183016763267, 'logit_2': -2.032090999429684, 'logit_3': -2.0448925700506777, 'logit_4': -3.3289913980039896, 'logit_5': 1.4450786962130593, 'logit_6': 0.604679853444672, 'logit_7': 3.9906708249771894, 'logit_8': -2.1985643889838355, 'logit_9': 3.5052495527167165, 'logit_10': 2.238106716903845}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:38,409] Trial 35 finished with value: 0.4585948313478062 and parameters: {'logit_0': 1.3442270014458306, 'logit_1': 1.5414002693749915, 'logit_2': -3.3140183811037875, 'logit_3': -3.952364596152392, 'logit_4': -2.49074131900503, 'logit_5': 2.218445378634492, 'logit_6': -0.6815783861908911, 'logit_7': 1.7122050598408614, 'logit_8': 0.792116634626664, 'logit_9': 2.1313392312210198, 'logit_10': 3.511762644702355}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:43,947] Trial 36 finished with value: 0.4417103452209298 and parameters: {'logit_0': -1.3260063260543364, 'logit_1': 2.8741726854085745, 'logit_2': -2.700940276217933, 'logit_3': -2.413652976928492, 'logit_4': -1.8099553236685233, 'logit_5': 1.1414135253002688, 'logit_6': -1.4239830074514932, 'logit_7': -0.4974352940568991, 'logit_8': 2.002203353272639, 'logit_9': 1.2492249655970358, 'logit_10': 3.056053126417683}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:49,315] Trial 37 finished with value: 0.4608841169774901 and parameters: {'logit_0': -0.4157168641865082, 'logit_1': -0.5073249720511217, 'logit_2': -1.1003369080736625, 'logit_3': -1.608985567956395, 'logit_4': -1.1691950987735487, 'logit_5': 2.9387072107961183, 'logit_6': -2.490977528842561, 'logit_7': 2.603834657664246, 'logit_8': -0.3618199827798809, 'logit_9': 0.6372728452762446, 'logit_10': 3.4241890824352526}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:50:54,800] Trial 38 finished with value: 0.45749614298103153 and parameters: {'logit_0': 0.5486953811635437, 'logit_1': 2.5175436290044493, 'logit_2': 0.6312400272801041, 'logit_3': -3.055916452660446, 'logit_4': -3.5663004810424384, 'logit_5': 0.18931675106496426, 'logit_6': 1.3073418664528456, 'logit_7': 0.7359531685638012, 'logit_8': 1.2282480074589275, 'logit_9': 2.9134802951882404, 'logit_10': 3.995847181083983}. Best is trial 23 with value: 0.4636227016433492.
[I 2026-07-30 09:51:00,152] Trial 39 finished with value: 0.44634942661464916 and parameters: {'logit_0': 2.2691027299085054, 'logit_1': 0.530614884130008, 'logit_2': -2.562798514369377, 'logit_3': -3.4960813439290974, 'logit_4': -2.7095381705911596, 'logit_5': 3.565354533074221, 'logit_6': -0.20608207485938057, 'logit_7': -3.917764997346736, 'logit_8': 0.23805122713154003, 'logit_9': 1.7607340751308813, 'logit_10': 1.80964680781629}. Best is trial 23 with value: 0.4636227016433492.

              feature         rank_feature    weight  direction
9            range_20           r_range_20  0.546172          1
8      turnover_accel     r_turnover_accel  0.246163          1
5       volatility_20      r_volatility_20  0.119976          1
10        drawdown_60        r_drawdown_60  0.050262         -1
7         volume_z_20        r_volume_z_20  0.021641          1
3             abret_5            r_abret_5  0.004253          1
0               mom_5              r_mom_5  0.003909          1
2              mom_60             r_mom_60  0.003396          1
6   volume_ratio_5_60  r_volume_ratio_5_60  0.003028          1
4            abret_20           r_abret_20  0.000893          1
1              mom_20             r_mom_20  0.000306          1

                 2026 untouched test
pr_auc                      0.252129
ndcg_at_50                  0.539188
precision_at_50             0.321488
lift_at_50                  2.190012

## 8. Validation proxy: suspected suspension dalam 20 hari bursa

Karena riwayat UMA resmi belum tersedia, validasi tambahan memakai **proxy suspected suspension** dari sesi tidak aktif di Parquet. Event dimulai ketika ticker kehilangan bar atau mencatat volume nol minimal 3 sesi IHSG berturut-turut, dengan sesi aktif sebelum dan sesudah rangkaian tersebut. Ini bukan UMA resmi: pola serupa dapat berasal dari masalah Yahoo, saham sangat tidak likuid, atau perubahan ticker.

In [13]:
MIN_MISSING_SESSIONS = 3

def suspension_proxy_events(price_panel, benchmark_dates, min_missing=3):
    """Cari run bar hilang/volume nol yang diapit sesi bervolume positif."""
    calendar = pd.DatetimeIndex(sorted(pd.to_datetime(benchmark_dates).unique()))
    event_positions = {}
    event_rows = []

    for ticker, g in tqdm(price_panel.groupby('ticker'), desc='Detect suspension proxy', unit='ticker'):
        g = g[['date','volume']].drop_duplicates('date').set_index('date').sort_index()
        observed_dates = calendar.intersection(g.index)
        if len(observed_dates) < 2:
            event_positions[ticker] = np.array([], dtype=int)
            continue

        first = calendar.searchsorted(observed_dates.min())
        last = calendar.searchsorted(observed_dates.max())
        volume = g['volume'].reindex(calendar)
        inactive = (volume.isna() | volume.le(0)).to_numpy()
        inactive[:first + 1] = False
        inactive[last:] = False

        padded = np.r_[False, inactive, False]
        starts = np.flatnonzero(~padded[:-1] & padded[1:])
        ends = np.flatnonzero(padded[:-1] & ~padded[1:]) - 1
        confirmed = [(s, e) for s, e in zip(starts, ends)
                     if (e - s + 1) >= min_missing
                     and s > first and e < last
                     and pd.notna(volume.iloc[s - 1]) and volume.iloc[s - 1] > 0
                     and pd.notna(volume.iloc[e + 1]) and volume.iloc[e + 1] > 0]
        event_positions[ticker] = np.array([s for s, _ in confirmed], dtype=int)
        for start, end in confirmed:
            block = volume.iloc[start:end + 1]
            event_rows.append({
                'ticker': ticker,
                'proxy_start': calendar[start],
                'inactive_sessions': int(end - start + 1),
                'missing_bar_sessions': int(block.isna().sum()),
                'zero_volume_sessions': int(block.fillna(1).le(0).sum()),
                'last_active_before': calendar[start - 1],
                'first_active_after': calendar[end + 1]
            })
    event_columns = [
        'ticker', 'proxy_start', 'inactive_sessions', 'missing_bar_sessions',
        'zero_volume_sessions', 'last_active_before', 'first_active_after'
    ]
    return event_positions, pd.DataFrame(event_rows, columns=event_columns), calendar

def attach_future_suspension_proxy(scored, event_positions, calendar, horizon=20):
    out = scored.copy()
    labels = np.full(len(out), -1, dtype=np.int8)
    for i, (ticker, d) in enumerate(tqdm(zip(out.ticker, out.date), total=len(out), desc='Proxy labels')):
        pos = calendar.searchsorted(d)
        if pos >= len(calendar) or calendar[pos] != d or pos + horizon >= len(calendar):
            continue  # horizon belum observable
        events = event_positions.get(ticker, np.array([], dtype=int))
        left = np.searchsorted(events, pos + 1)
        labels[i] = int(left < len(events) and events[left] <= pos + horizon)
    out['suspected_suspension_next_20d'] = labels
    return out

if 'final_scored' not in globals():
    print('Final test belum tersedia.')
else:
    event_positions, proxy_events, trading_calendar = suspension_proxy_events(
        stocks[['ticker','date','volume']], bench['date'], MIN_MISSING_SESSIONS
    )
    proxy_events.to_csv(OUTPUT_DIR / 'suspected_suspension_events.csv', index=False)
    proxy_scored = attach_future_suspension_proxy(final_scored, event_positions, trading_calendar, HORIZON)
    observable = proxy_scored[proxy_scored.suspected_suspension_next_20d >= 0].copy()
    validation = observable.rename(columns={'target': 'price_volume_target'})
    validation['target'] = validation['suspected_suspension_next_20d']
    proxy_pr_auc = (average_precision_score(validation.target, validation.score)
                    if validation.target.nunique() > 1 else np.nan)
    proxy_topk = datewise_topk_metrics(validation).mean(numeric_only=True).to_dict()
    print({'proxy_suspension_pr_auc': proxy_pr_auc,
           'proxy_event_rate': validation.target.mean(),
           'detected_gap_events': len(proxy_events), **proxy_topk})
    if proxy_events.empty:
        print(f'Tidak ada confirmed gap minimal {MIN_MISSING_SESSIONS} sesi yang kemudian kembali diperdagangkan.')
    else:
        display(proxy_events.sort_values('proxy_start', ascending=False).head(20))

Detect suspension proxy:   0%|          | 0/958 [00:00<?, ?ticker/s]

Proxy labels:   0%|          | 0/108150 [00:00<?, ?it/s]

{'proxy_suspension_pr_auc': 0.0347809009880605, 'proxy_event_rate': 0.014450506774574013, 'detected_gap_events': 2851, 'precision_at_50': 0.05894736842105264, 'ndcg_at_50': 0.30687056571868876, 'lift_at_50': 3.668366892979939}

,ticker,proxy_start,inactive_sessions,missing_bar_sessions,zero_volume_sessions,last_active_before,first_active_after
470,BSWD,2026-07-20,6,0,6,2026-07-17,2026-07-28
953,FLMC,2026-07-03,10,0,10,2026-07-02,2026-07-17
2199,SINI,2026-07-01,4,0,4,2026-06-30,2026-07-07
2847,ZATA,2026-06-30,16,0,16,2026-06-29,2026-07-22
92,AIMS,2026-06-30,9,0,9,2026-06-29,2026-07-13
622,COAL,2026-06-30,12,0,12,2026-06-29,2026-07-16
313,BLTZ,2026-06-30,10,0,10,2026-06-29,2026-07-14
140,ASMI,2026-06-30,7,0,7,2026-06-29,2026-07-09
2611,TFCO,2026-06-29,3,0,3,2026-06-26,2026-07-02
1894,PDES,2026-06-26,4,0,4,2026-06-25,2026-07-02
312,BLTZ,2026-06-22,5,0,5,2026-06-19,2026-06-29
469,BSWD,2026-06-17,12,0,12,2026-06-15,2026-07-03
964,FORU,2026-06-15,6,0,6,2026-06-12,2026-06-24
2191,SHIP,2026-06-09,8,0,8,2026-06-08,2026-06-22
1720,MMIX,2026-06-08,6,0,6,2026-06-05,2026-06-17
233,BBMD,2026-06-03,6,0,6,2026-06-02,2026-06-11
311,BLTZ,2026-06-02,9,0,9,2026-05-29,2026-06-15
271,BKDP,2026-05-29,20,0,20,2026-05-26,2026-06-30
468,BSWD,2026-05-26,11,0,11,2026-05-25,2026-06-15
1372,KING,2026-05-25,10,0,10,2026-05-22,2026-06-11

## 9. Kandidat operasional terbaru

Semua ticker—termasuk IDX80/LQ45—mendapat skor. Filter kontrol baru diterapkan setelah scoring. Output final berisi maksimum 50 kandidat non-kontrol.

In [17]:
latest_date = panel.loc[panel[RANK_FEATURES].notna().any(axis=1), 'date'].max()
latest = panel[panel.date.eq(latest_date)].copy()
latest_scored = score_frame(latest, final_weights, final_directions)

def active_control_flags(rows, controls):
    if controls.empty:
        return pd.Series(False, index=rows.index)
    keys = controls[['ticker','effective_from','effective_to']].copy()
    merged = rows[['ticker','date']].reset_index().merge(keys, on='ticker', how='left')
    active = ((merged.effective_from.isna() | (merged.date >= merged.effective_from)) &
              (merged.effective_to.isna() | (merged.date <= merged.effective_to)) &
              merged.ticker.isin(set(keys.ticker)))
    return active.groupby(merged['index']).any().reindex(rows.index, fill_value=False)

latest_scored['is_idx80_or_lq45'] = active_control_flags(latest_scored, controls)
all_scores = latest_scored.sort_values('score', ascending=False)
candidates = all_scores[~all_scores.is_idx80_or_lq45].head(TOP_K).copy()
cols = ['date','ticker','sector','subsector','score','is_idx80_or_lq45'] + FEATURES
candidates[cols].to_csv(OUTPUT_DIR / f'candidates_{latest_date:%Y%m%d}.csv', index=False)
all_scores[['date','ticker','sector','subsector','score','is_idx80_or_lq45']].to_csv(
    OUTPUT_DIR / f'all_scores_{latest_date:%Y%m%d}.csv', index=False
)
print(f'Scoring date: {latest_date:%Y-%m-%d} | final candidates: {len(candidates)}')
display(candidates[cols[:6]].reset_index(drop=True))

Scoring date: 2026-07-30 | final candidates: 50

,date,ticker,sector,subsector,score,is_idx80_or_lq45
0,2026-07-30,MCAS,Teknologi,Perangkat Lunak & Jasa TI,0.979100,False
1,2026-07-30,MGNA,Barang Konsumen Non-Primer,Jasa Konsumen,0.960421,False
2,2026-07-30,MPRO,Properti & Real Estat,Properti & Real Estat,0.957295,False
3,2026-07-30,KDTN,Barang Konsumen Non-Primer,Jasa Konsumen,0.956690,False
4,2026-07-30,DMMX,Teknologi,Perangkat Lunak & Jasa TI,0.951431,False
5,2026-07-30,BAJA,Barang Baku,Barang Baku,0.946808,False
6,2026-07-30,MLPT,Teknologi,Perangkat Lunak & Jasa TI,0.943129,False
7,2026-07-30,COCO,Barang Konsumen Primer,Makanan & Minuman,0.940428,False
8,2026-07-30,ZONE,Barang Konsumen Non-Primer,Perdagangan Ritel,0.936922,False
9,2026-07-30,MDIA,Barang Konsumen Non-Primer,Media & Hiburan,0.929908,False
10,2026-07-30,KOKA,Infrastruktur,Konstruksi Bangunan,0.922691,False
11,2026-07-30,DWGL,Energi,"Minyak, Gas & Batu Bara",0.920361,False
12,2026-07-30,INAI,Barang Baku,Barang Baku,0.920035,False
13,2026-07-30,ECII,Barang Konsumen Non-Primer,Perdagangan Ritel,0.918317,False
14,2026-07-30,DOOH,Barang Konsumen Non-Primer,Media & Hiburan,0.918236,False
15,2026-07-30,KOBX,Perindustrian,Barang Perindustrian,0.915750,False
16,2026-07-30,PSDN,Barang Konsumen Primer,Makanan & Minuman,0.913928,False
17,2026-07-30,NTBK,Perindustrian,Barang Perindustrian,0.907961,False
18,2026-07-30,FUTR,Barang Konsumen Non-Primer,Media & Hiburan,0.905855,False
19,2026-07-30,LUCY,Barang Konsumen Non-Primer,Jasa Konsumen,0.902767,False
20,2026-07-30,JGLE,Barang Konsumen Non-Primer,Jasa Konsumen,0.901432,False
21,2026-07-30,DEPO,Barang Konsumen Non-Primer,Perdagangan Ritel,0.901177,False
22,2026-07-30,SQMI,Barang Baku,Barang Baku,0.901092,False
23,2026-07-30,TAMA,Infrastruktur,Konstruksi Bangunan,0.897353,False
24,2026-07-30,FLMC,Barang Konsumen Primer,Produk Rumah Tangga Tidak Tahan Lama,0.897195,False
25,2026-07-30,TNCA,Transportasi & Logistik,Logistik & Pengantaran,0.896202,False
26,2026-07-30,KBLV,Infrastruktur,Telekomunikasi,0.895170,False
27,2026-07-30,KLIN,Barang Konsumen Non-Primer,Perdagangan Ritel,0.892380,False
28,2026-07-30,GDST,Barang Baku,Barang Baku,0.891628,False
29,2026-07-30,KOTA,Barang Konsumen Non-Primer,Jasa Konsumen,0.891510,False
30,2026-07-30,PEGE,Keuangan,Perusahaan Holding & Investasi,0.890194,False
31,2026-07-30,SULI,Barang Baku,Barang Baku,0.889072,False
32,2026-07-30,MMIX,Kesehatan,Jasa & Peralatan Kesehatan,0.888776,False
33,2026-07-30,TFAS,Teknologi,Perangkat Lunak & Jasa TI,0.887600,False
34,2026-07-30,ZATA,Barang Konsumen Non-Primer,Perdagangan Ritel,0.887048,False
35,2026-07-30,WOOD,Barang Konsumen Non-Primer,Barang Rumah Tangga,0.886273,False
36,2026-07-30,LAND,Properti & Real Estat,Properti & Real Estat,0.885854,False
37,2026-07-30,KOPI,Energi,"Minyak, Gas & Batu Bara",0.885691,False
38,2026-07-30,HOPE,Perindustrian,Barang Perindustrian,0.884694,False
39,2026-07-30,FILM,Barang Konsumen Non-Primer,Media & Hiburan,0.882089,False
40,2026-07-30,PTMP,Perindustrian,Barang Perindustrian,0.881727,False
41,2026-07-30,OILS,Barang Konsumen Primer,Makanan & Minuman,0.880094,False
42,2026-07-30,TRUS,Keuangan,Jasa Pembiayaan,0.878915,False
43,2026-07-30,ALDO,Barang Baku,Barang Baku,0.876374,False
44,2026-07-30,DIVA,Teknologi,Perangkat Lunak & Jasa TI,0.875040,False
45,2026-07-30,LION,Perindustrian,Jasa Perindustrian,0.874809,False
46,2026-07-30,RLCO,Barang Konsumen Primer,Makanan & Minuman,0.869934,False
47,2026-07-30,NANO,Barang Konsumen Primer,Produk Rumah Tangga Tidak Tahan Lama,0.869686,False
48,2026-07-30,ELPI,Transportasi & Logistik,Logistik & Pengantaran,0.868137,False
49,2026-07-30,RONY,Infrastruktur,Konstruksi Bangunan,0.865881,False

In [19]:
list(candidates['ticker'])

['MCAS',
 'MGNA',
 'MPRO',
 'KDTN',
 'DMMX',
 'BAJA',
 'MLPT',
 'COCO',
 'ZONE',
 'MDIA',
 'KOKA',
 'DWGL',
 'INAI',
 'ECII',
 'DOOH',
 'KOBX',
 'PSDN',
 'NTBK',
 'FUTR',
 'LUCY',
 'JGLE',
 'DEPO',
 'SQMI',
 'TAMA',
 'FLMC',
 'TNCA',
 'KBLV',
 'KLIN',
 'GDST',
 'KOTA',
 'PEGE',
 'SULI',
 'MMIX',
 'TFAS',
 'ZATA',
 'WOOD',
 'LAND',
 'KOPI',
 'HOPE',
 'FILM',
 'PTMP',
 'OILS',
 'TRUS',
 'ALDO',
 'DIVA',
 'LION',
 'RLCO',
 'NANO',
 'ELPI',
 'RONY']

## Checklist sebelum produksi

- Isi dan audit riwayat `control_universe.csv`; jangan hanya memakai snapshot jika backtest filter kontrol ikut dilaporkan.
- Audit `suspected_suspension_events.csv`; proxy gap Yahoo bukan bukti suspend atau UMA resmi.
- Periksa `outputs/missing_yfinance.csv`; delisting, IPO baru, ticker berubah, dan data volume nol perlu perlakuan eksplisit.
- Laporkan prevalence target, coverage universe, PR-AUC, Precision@50, Lift@50, serta interval kepercayaan bootstrap per tanggal.
- Jangan mengulang tuning setelah melihat final test 2026. Buat versi eksperimen baru bila definisi target atau fitur berubah.
- Skor adalah alat penyaringan riset, bukan rekomendasi investasi.